<?php
/**
 * Language labels for plugin "tx_rlmpdateselectlib"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'weekdays_sunday' => 'Sunday',
		'weekdays_monday' => 'Monday',
		'weekdays_tuesday' => 'Tuesday',
		'weekdays_wednesday' => 'Wednesday',
		'weekdays_thursday' => 'Thursday',
		'weekdays_friday' => 'Friday',
		'weekdays_saturday' => 'Saturday',
		'shortweekdays_sunday' => 'Sun',
		'shortweekdays_monday' => 'Mon',
		'shortweekdays_tuesday' => 'Tue',
		'shortweekdays_wednesday' => 'Wed',
		'shortweekdays_thursday' => 'Thu',
		'shortweekdays_friday' => 'Fri',
		'shortweekdays_saturday' => 'Sat',
		'months_january' => 'January',
		'months_february' => 'February',
		'months_march' => 'March',
		'months_april' => 'April',
		'months_may' => 'May',
		'months_june' => 'June',
		'months_july' => 'July',
		'months_august' => 'August',
		'months_september' => 'September',
		'months_october' => 'October',
		'months_november' => 'November',
		'months_december' => 'December',
		'shortmonths_january' => 'Jan',
		'shortmonths_february' => 'Feb',
		'shortmonths_march' => 'Mar',
		'shortmonths_april' => 'Apr',
		'shortmonths_may' => 'May',
		'shortmonths_june' => 'Jun',
		'shortmonths_july' => 'Jul',
		'shortmonths_august' => 'Aug',
		'shortmonths_september' => 'Sep',
		'shortmonths_october' => 'Oct',
		'shortmonths_november' => 'Nov',
		'shortmonths_december' => 'Dec',
		'tt_about' => 'DHTML Date/Time Selector (c) dynarch.com 2002-2003 For latest version visit: http://dynarch.com/mishoo/calendar.epl Distributed under GNU LGPL.  See http://gnu.org/licenses/lgpl.html for details.',
		'tt_toggle_first_day_of_week' => 'Toggle first day of week',
		'tt_previous_year' => 'Prev. year (hold for menu)',
		'tt_previous_month' => 'Prev. month (hold for menu)',
		'tt_go_today' => 'Go Today',
		'tt_next_month' => 'Next month (hold for menu)',
		'tt_next_year' => 'Next year (hold for menu)',
		'tt_select_date' => 'Select date',
		'tt_drag_to_move' => 'Drag to move',
		'tt_part_today' => 'today',
		'tt_display_day_first' => 'Toggle: Week starts with %s',
		'tt_close' => 'Close',
		'tt_today' => 'Today',
		'week' => 'wk',
		'monday_first' => 'false',
		'dateTimeFormat' => '%Y-%m-%d',
		'toolTipDateTimeFormat' => '%A, %B %e',
	),
	'dk' => Array (
	),
	'de' => Array (
		'weekdays_sunday' => 'Sonntag',
		'weekdays_monday' => 'Montag',
		'weekdays_tuesday' => 'Dienstag',
		'weekdays_wednesday' => 'Mittwoch',
		'weekdays_thursday' => 'Donnerstag',
		'weekdays_friday' => 'Freitag',
		'weekdays_saturday' => 'Samstag',
		'shortweekdays_sunday' => 'So',
		'shortweekdays_monday' => 'Mo',
		'shortweekdays_tuesday' => 'Di',
		'shortweekdays_wednesday' => 'Mi',
		'shortweekdays_thursday' => 'Do',
		'shortweekdays_friday' => 'Fr',
		'shortweekdays_saturday' => 'Sa',
		'months_january' => 'Januar',
		'months_february' => 'Februar',
		'months_march' => 'März',
		'months_april' => 'April',
		'months_may' => 'Mai',
		'months_june' => 'Juni',
		'months_july' => 'Juli',
		'months_august' => 'August',
		'months_september' => 'September',
		'months_october' => 'Oktober',
		'months_november' => 'November',
		'months_december' => 'Dezember',
		'shortmonths_january' => 'Jan',
		'shortmonths_february' => 'Feb',
		'shortmonths_march' => 'Mär',
		'shortmonths_april' => 'Apr',
		'shortmonths_may' => 'Mai',
		'shortmonths_june' => 'Jun',
		'shortmonths_july' => 'Jul',
		'shortmonths_august' => 'Aug',
		'shortmonths_september' => 'Sep',
		'shortmonths_october' => 'Okt',
		'shortmonths_november' => 'Nov',
		'shortmonths_december' => 'Dez',
		'tt_toggle_first_day_of_week' => 'Ersten Tag der Woche ändern',
		'tt_previous_year' => 'Vorheriges Jahr (halten für Menü)',
		'tt_previous_month' => 'Nächstes Jahr (halten für Menü)',
		'tt_go_today' => 'Springe zu Heute',
		'tt_next_month' => 'Nächster Monat (halten für Menü)',
		'tt_next_year' => 'Nächstes Jahr (halten für Menü)',
		'tt_select_date' => 'Datum wählen',
		'tt_drag_to_move' => 'Zum Bewegen Maus gedrückt halten',
		'tt_part_today' => 'heute',
		'tt_display_day_first' => 'Umschalten: Woche beginnt mit %s',
		'tt_close' => 'Schließen',
		'tt_today' => 'Heute',
		'week' => 'KW',
		'monday_first' => 'true',
		'dateTimeFormat' => '%d.%m.%Y',
		'toolTipDateTimeFormat' => '%A, %e. %B',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
		'weekdays_sunday' => 'Zondag',
		'weekdays_monday' => 'Maandag',
		'weekdays_tuesday' => 'Dinsdag',
		'weekdays_wednesday' => 'Woensdag',
		'weekdays_thursday' => 'Donderdag',
		'weekdays_friday' => 'Vrijdag',
		'weekdays_saturday' => 'Zaterdag',
		'months_january' => 'Januari',
		'months_february' => 'Februari',
		'months_march' => 'Maart',
		'months_april' => 'April',
		'months_may' => 'Mei',
		'months_june' => 'Juni',
		'months_july' => 'Juli',
		'months_august' => 'Augustus',
		'months_september' => 'September',
		'months_october' => 'Oktober',
		'months_november' => 'November',
		'months_december' => 'December',
		'tt_toggle_first_day_of_week' => 'Wissel eerste dag van de week',
		'tt_previous_year' => 'Vorig jaar (klik voor menu)',
		'tt_previous_month' => 'Volgend jaar (klik voor menu)',
		'tt_go_today' => 'Ga naar vandaag',
		'tt_next_month' => 'Volgende maand (klik voor menu)',
		'tt_next_year' => 'Volgende maand (klik voor menu)',
		'tt_select_date' => 'Selecteer datum',
		'tt_drag_to_move' => 'Sleep om te verplaatsen',
		'tt_part_today' => 'vandaag',
		'tt_close' => 'Sluit',
		'tt_today' => 'Vandaag',
		'week' => 'wk',
	),
	'cz' => Array (
	),
	'pl' => Array (
		'weekdays_sunday' => 'Niedziela',
		'weekdays_monday' => 'Poniedzia³ek',
		'weekdays_tuesday' => 'Wtorek',
		'weekdays_wednesday' => '¦roda',
		'weekdays_thursday' => 'Czwartek',
		'weekdays_friday' => 'Pi±tek',
		'weekdays_saturday' => 'Sobota',
		'months_january' => 'Styczeñ',
		'months_february' => 'Luty',
		'months_march' => 'Marzec',
		'months_april' => 'Kwiecieñ',
		'months_may' => 'May',
		'months_june' => 'Czerwiec',
		'months_july' => 'Lipiec',
		'months_august' => 'Sierpieñ',
		'months_september' => 'Wrzesieñ',
		'months_october' => 'Pa¼dziernik',
		'months_november' => 'Listopad',
		'months_december' => 'Grudzieñ',
		'tt_toggle_first_day_of_week' => 'Prze³±cz pierwszy dzieñ tygodnia',
		'tt_previous_year' => 'Poprzedni rok (przytrzymanie - menu)',
		'tt_previous_month' => 'Poprzedni rok (przytrzymanie - menu)',
		'tt_go_today' => 'Dzisiaj',
		'tt_next_month' => 'Nastêpny miesi±c (przytrzymanie - menu)',
		'tt_next_year' => 'Nastêpny rok (przytrzymanie - menu)',
		'tt_select_date' => 'Wybierz datê',
		'tt_drag_to_move' => 'Przeci±gnij aby przej¶æ',
		'tt_part_today' => 'dzi¶',
		'tt_close' => 'Zamknij',
		'tt_today' => 'Dzi¶',
		'week' => 'tydz.',
		'monday_first' => 'fa³sz',
	),
	'si' => Array (
	),
	'fi' => Array (
		'weekdays_sunday' => 'Sunnuntai',
		'weekdays_monday' => 'Maanantai',
		'weekdays_tuesday' => 'Tiistai',
		'weekdays_wednesday' => 'Keskiviikko',
		'weekdays_thursday' => 'Torstai',
		'weekdays_friday' => 'Perjantai',
		'weekdays_saturday' => 'Lauantai',
		'months_january' => 'Tammikuu',
		'months_february' => 'Helmikuu',
		'months_march' => 'Malliskuu',
		'months_april' => 'Huhtikuu',
		'months_may' => 'Toukokuu',
		'months_june' => 'Kesäkuu',
		'months_july' => 'Heinäkuu',
		'months_august' => 'Elokuu',
		'months_september' => 'Syyskuu',
		'months_october' => 'Lokakuu',
		'months_november' => 'Marraskuu',
		'months_december' => 'Joulukuu',
		'tt_toggle_first_day_of_week' => 'Vaihda viikon ensimmäinen päivä',
		'tt_previous_year' => 'Ensimmäinen vuosi (pidetään vaikossa)',
		'tt_previous_month' => 'Viimeinen kuukausi  (pidetään vaikossa)',
		'tt_go_today' => 'Siirry päivään',
		'tt_next_month' => 'Seuraava kuukausi (pidetään vaikossa)',
		'tt_next_year' => 'Seuraava vuosi (pidetään vaikossa)',
		'tt_select_date' => 'Valitse päivä',
		'tt_drag_to_move' => 'Vedä siirtääksesi',
		'tt_part_today' => 'tänään',
		'tt_close' => 'Sulje',
		'tt_today' => 'Tänään',
		'week' => 'viikko',
		'monday_first' => 'false',
	),
	'tr' => Array (
	),
	'se' => Array (
		'weekdays_sunday' => 'Söndag',
		'weekdays_monday' => 'Måndag',
		'weekdays_tuesday' => 'Tisdag',
		'weekdays_wednesday' => 'Onsdag',
		'weekdays_thursday' => 'Torsdag',
		'weekdays_friday' => 'Fredag',
		'weekdays_saturday' => 'Lördag',
		'months_january' => 'Januari',
		'months_february' => 'Februari',
		'months_march' => 'Mars',
		'months_april' => 'April',
		'months_may' => 'Maj',
		'months_june' => 'Juni',
		'months_july' => 'Juli',
		'months_august' => 'Augusti',
		'months_september' => 'September',
		'months_october' => 'Oktober',
		'months_november' => 'November',
		'months_december' => 'December',
		'tt_toggle_first_day_of_week' => 'Första dagen i veckan',
		'tt_previous_year' => 'Föregående år (håll för meny)',
		'tt_previous_month' => 'Föregående månad (håll för meny)',
		'tt_go_today' => 'Gå till idag',
		'tt_next_month' => 'Nästa månad (håll för meny)',
		'tt_next_year' => 'Nästa år (håll för meny)',
		'tt_select_date' => 'Välj datum',
		'tt_drag_to_move' => 'Dra för att flytta',
		'tt_part_today' => 'idag',
		'tt_close' => 'Stäng',
		'tt_today' => 'Idag',
		'week' => 'vk',
		'monday_first' => 'falsk',
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>