<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'dmail_folders' => 'Available Direct Mail folders',
		'dmail_noCreateAccess' => 'You cannot mail pages that are hidden or access-restricted.',
		'dmail_noRegular' => 'This pagetype cannot be sent as an email. Please select a regular page.',
		'dmail_dovsk_selectDmail' => 'Select Direct Mail',
		'dmail_dovsk_crFromNL' => 'Create a new Direct Mail from newsletter',
		'dmail_msg1_crFromNL' => 'There are no newsletters which are not present as a Direct Mail already!',
		'dmail_dovsk_crFromUrl' => 'Create a new Direct Mail from external URL',
		'dmail_createMail' => 'Create mail',
		'dmail_view' => 'View direct mail record',
		'dmail_noEdit_noPerms' => 'Cannot edit - you don\'t have permissions to edit Direct Mails.',
		'dmail_noEdit_isSent' => 'Cannot edit - mail has been sent',
		'dmail_basedOn' => 'The Direct Mail is based on this page/newsletter.<br />Click to see page info:',
		'dmail_menu_newsletters' => 'Newsletters',
		'dmail_menu_direct_mails' => 'Direct Mails',
		'dmail_menu_quickMail' => 'QuickMail',
		'dmail_menu_list' => 'Recipient list',
		'dmail_menu_conf' => 'Module configuration',
		'dmail_menu_mailerengine' => 'Mailer Engine Status',
		'dmail_menu_help' => 'Instructions',
		'dmail_menu_convert_categories' => 'Categories conversion',
		'dmailer_mid' => 'Job No:',
		'dmailer_job_begin' => 'Job begin',
		'dmailer_job_end' => 'Job end',
		'dmailer_invoked_at' => 'Invoked at',
		'dmailer_nothing_to_do' => 'Nothing to do.',
		'dmailer_ending' => 'Ending, parsetime:',
		'dmailer_sys_dmail_record' => 'sys_dmail record',
		'dmailer_processed' => 'processed...',
		'dmail_menuItems' => '[MENU]',
		'dmail_menuItems_prefetch' => 'Fetch and compile maildata (read url)',
		'dmail_menuItems_testmail' => 'Send a testmail',
		'dmail_menuItems_finalmail' => 'Mass-send mail',
		'dmail_menuItems_stats' => 'See statistics of this mail',
		'dmail_menuItems_options' => 'Options:',
		'dmail_menuItems_note' => 'Note:',
		'dmail_menuItems_note_use_menu' => 'Use the menu to fetch content for the email',
		'dmail_menuItems_note_enter_sender' => 'You must enter a \'Sender email\' address for the mail!',
		'dmail_menuItems_note_send_test' => 'Use the menu to send a test-mail to your own email address or finally send the mail to all recipients.',
		'dmail_back' => '< BACK',
		'dmail_yes' => 'YES',
		'dmail_no' => 'NO',
		'dmail_error' => 'ERROR',
		'dmail_send' => 'Send',
		'dmail_edit' => 'Edit',
		'dmail_cancel' => 'Cancel',
		'dmail_number_records' => 'Number of records:',
		'dmail_subject' => 'Subject:',
		'dmail_write_subject' => '[write subject]',
		'dmail_HTML_url' => 'HTML URL:',
		'dmail_plaintext_url' => 'Plain Text URL:',
		'dmail_mailerengine_subject' => 'Subject',
		'dmail_mailerengine_scheduled' => 'Scheduled',
		'dmail_mailerengine_delivery_begun' => 'Delivery begun',
		'dmail_mailerengine_delivery_ended' => 'Delivery ended',
		'dmail_mailerengine_number_sent' => '# sent',
		'dmail_mailerengine_invoked' => 'Mailer Engine Invoked!',
		'dmail_mailerengine_status' => 'Mail Engine Status',
		'dmail_mailerengine_current_time' => 'Current time:',
		'dmail_mailerengine_manual_invoke' => 'Manually Invoke Engine',
		'dmail_mailerengine_manual_explain' => 'If Typo3 is not configured to automatically invoke the Mailer Engine, you can invoke it by clicking here:',
		'dmail_mailerengine_invoke_now' => 'Invoke Mailer Engine',
		'dmail_mailerengine_log' => 'Log:',
		'mailgroup_recip_from' => 'Recipients from group:',
		'mailgroup_recip_number' => 'Number of recipients:',
		'mailgroup_list_all' => 'List all recipients',
		'mailgroup_table_address' => 'Address Table',
		'mailgroup_table_fe_users' => 'Website User Table',
		'mailgroup_plain_list' => 'Plain List',
		'mailgroup_table_custom' => 'Custom Table',
		'mailgroup_download' => 'Download CSV file',
		'mailgroup_import' => 'Import CSV into \'ADDRESS\' table',
		'mailgroup_import_rules' => 'Rules:',
		'mailgroup_import_test' => 'Test import (no data written)',
		'mailgroup_import_now' => 'Import now!',
		'recip_select_mailgroup' => 'Select a Mail Group',
		'recip_create_mailgroup' => 'New mail group',
		'recip_create_mailgroup_msg' => 'Create new group?',
		'recip_import_mailgroup' => 'Import',
		'recip_import_mailgroup_msg' => 'Click here to import CSV',
		'prefetch_read_url' => 'You\'re about to read the url with the mail-content from these URL\'s:',
		'prefetch_fetching' => 'Fetching the mail content',
		'prefetch_patience' => 'This operation may take a while. Therefore be patient.',
		'prefetch_fetch' => 'Read URL',
		'prefetch_error_choose' => 'You must choose to send either HTML, plaintext or both. Nothing is selected at this time!',
		'testmail_individual' => 'Testmail - Individual',
		'testmail_individual_msg' => 'Select a recipient of the testmail. The mail will be generated based on the profile of the recipient you select.',
		'testmail_mailgroup' => 'Testmail - Direct Mail Group',
		'testmail_mailgroup_msg' => 'Select a recipient mail group for the testmail. The mails will be generated based on the profiles of the recipients in that group.',
		'testmail_simple' => 'Testmail - Simple',
		'testmail_simple_msg' => 'A simple testmail includes all mail elements regardless of category. But any USER_fields are not substituted with data. Enter an email-address for the testmail:',
		'send_sending' => 'Sending mail',
		'send_was_sent' => 'The mail was sent.',
		'send_was_sent_to_name' => 'The mail was sent to <strong>%s</strong>.',
		'send_was_sent_to_number' => 'The mail was sent to <strong>%s</strong> recipients.',
		'send_recipients' => 'Recipients:',
		'send_was_scheduled' => 'Mail scheduled for distribution',
		'send_was_scheduled_for' => 'The mail was scheduled for distribution at',
		'schedule_select_mailgroup' => 'Select a Mail Group',
		'schedule_time' => 'Distribution time (hh:mm dd-mm-yy):',
		'schedule_send_all' => 'Send to all subscribers in mail group',
		'schedule_list_emails' => 'Send mail - list of emails',
		'schedule_enter_emails' => 'Enter the email-addresses for the recipients. Separate the addresses with linebreak or comma ",":',
		'quickmail_message' => 'Message:',
		'quickmail_sender_name' => 'Sender Name:',
		'quickmail_sender_email' => 'Sender Email:',
		'quickmail_one_mail_bcc' => 'One mail to all recipients in Blind Carbon Copy (Bcc)',
		'quickmail_one_mail_cc' => 'One mail to all recipients in Carbon Copy (Cc)',
		'quickmail_many_mails' => 'Many mails, one for each recipient',
		'quickmail_send_now' => 'Send message to all members of group immediately',
		'quickmail_break_lines' => 'Break lines to 76 char:',
		'quickmail_missing_fields' => 'You didn\'t fill in all the fields correctly!',
		'quickmail_sent_to' => 'Sent to:',
		'quickmail_copy_to' => 'Copy to:',
		'quickmail_mode' => 'Mode:',
		'quickmail_no_recipient' => 'No recipient.',
		'configure_direct_mail_module' => 'Configure direct mail module',
		'instructions_how' => 'How this works...',
		'instructions_text' => '
In this module you can create newsletters (pages), which can be emailed as \'direct mails\' to people on a subscription list.

To create a direct mail, you must follow these steps:
<B>1)</B> Select \'Newsletter\' in the menu above.
    <B>2)</B> Create a new \'newsletter\'. Put content in that newsletter, save it, preview it - exactly as you\'re used to with regular pages in Typo3. Actually a \'newsletter\' in this context is simply a Typo3 page destined for emailing!
    <B>3)</B> Click your new newsletter in the list. Now you can see information about that page, categorize the content elements.
    <B>4)</B> When your newsletter is ready to be distributed, click the link \'Create new direct mail based on this page\' and a new direct mail based on your newsletter is created.
    <B>5)</B> The first thing to do with your new \'Direct Mail\' is to fetch the mail content. This process reads the content from the page and compiles a mail out of it.
    <B>6)</B> Send a test. You should definitely send a testmail to yourself before mailing to your subscribers. Doing so, you can make sure that the mail and all links in it are correctly set up. Be aware if there are links to local network URLs. Those will not be accessible to the people receiving your newsletter!
    <B>7)</B> Initialize distribution if everything is OK.
    
    <B>The difference of a newsletter and a direct mail</B>
    A \'newsletter\' is basically a regular Typo3 page which resides here in the direct mail module. You can view the page in a browser and the point is that this page is finally send as a direct mail.
    A \'direct mail\' is a record that contains a compiled version of either a newsletter page or alternatively the content of an external url. In addition the direct mail contains information like the mail subject, any attachments, priority settings, reply addresses and all that. For each direct mail a log is kept of who has received the direct mail and if they responded to it.

    <B>Data fields in direct mails:</B>
    You can insert personalized data in the mails by inserting these markers:
    ###USER_uid### (the unique id of the recipient)
    ###USER_name### (full name)
    ###USER_firstname### (first name calculated)
    ###USER_title###
    ###USER_email###
    ###USER_phone###
    ###USER_www###
    ###USER_address###
    ###USER_company###
    ###USER_city###
    ###USER_zip###
    ###USER_country###
    ###USER_fax###
    
    ###SYS_TABLE_NAME###
    ###SYS_MAIL_ID###
    ###SYS_AUTHCODE###
    
    (In addition ###USER_NAME### and ###USER_FIRSTNAME### will insert uppercase versions of the equalents)
',
		'stats_general_information' => 'General information:',
		'stats_total' => 'Total:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Plaintext:',
		'stats_mails_sent' => 'Mails sent:',
		'stats_mails_returned' => 'Mails returned:',
		'stats_HTML_mails_viewed' => 'HTML mails viewed:',
		'stats_unique_responses' => 'Unique responses (link click):',
		'stats_response' => 'Response:',
		'stats_total_responses' => 'Total responses (link click):',
		'stats_links_clicked_per_respondent' => 'Links clicked per respondent:',
		'stats_count' => 'Count:',
		'stats_total_mails_returned' => 'Total mails returned:',
		'stats_recipient_unknown' => 'Recipient unknown:',
		'stats_mailbox_full' => 'Mailbox full:',
		'stats_bad_host' => 'Bad host:',
		'stats_error_in_header' => 'Error in Header:',
		'stats_reason_unkown' => 'Reason unknown:',
		'stats_list_returned' => 'List returned recipients',
		'stats_disable_returned' => 'Disable returned recipients',
		'stats_CSV_returned' => 'CSV of returned recipients',
		'stats_emails_returned_list' => 'Email adresses of returned mails:',
		'stats_mails_returned_unknown_recipient' => 'Mails returned with unknown recipient:',
		'stats_list_returned_unknown_recipient' => 'List returned recipients with unknown recipient',
		'stats_disable_returned_unknown_recipient' => 'Disable returned recipients with unknown recipient',
		'stats_CSV_returned_unknown_recipient' => 'CSV of returned recipients with unknown recipient',
		'stats_emails_returned_unknown_recipient_list' => 'Email adresses of returned mails with unknown recipient:',
		'stats_mails_returned_mailbox_full' => 'Mails returned with mailbox full:',
		'stats_list_returned_mailbox_full' => 'List returned recipients with mailbox full',
		'stats_disable_returned_mailbox_full' => 'Disable returned recipients with mailbox full',
		'stats_CSV_returned_mailbox_full' => 'CSV of returned recipients with mailbox full',
		'stats_emails_returned_mailbox_full_list' => 'Email adresses of returned mails with mailbox full:',
		'stats_mails_returned_bad_host' => 'Mails returned with bad host:',
		'stats_list_returned_bad_host' => 'List returned recipients with bad host',
		'stats_disable_returned_bad_host' => 'Disable returned recipients with bad host',
		'stats_CSV_returned_bad_host' => 'CSV of returned recipients with bad host',
		'stats_emails_returned_bad_host_list' => 'Email adresses of returned mails with bad host:',
		'stats_mails_returned_bad_header' => 'Mails returned with error in header:',
		'stats_list_returned_bad_header' => 'List returned recipients with error in header',
		'stats_disable_returned_bad_header' => 'Disable returned recipients with error in header',
		'stats_CSV_returned_bad_header' => 'CSV of returned recipients with error in header',
		'stats_emails_returned_bad_header_list' => 'Email adresses of returned mails with error in header:',
		'stats_mails_returned_reason_unknown' => 'Mails returned for unknown reason:',
		'stats_list_returned_reason_unknown' => 'List returned recipients for unknown reason',
		'stats_disable_returned_reason_unknown' => 'Disable returned recipients for unknown reason',
		'stats_CSV_returned_reason_unknown' => 'CSV of returned recipients for unknown reason',
		'stats_emails_returned_reason_unknown_list' => 'Email adresses of returned mails for unknown reason:',
		'stats_emails_disabled' => 'adresses disabled',
		'stats_website_users_disabled' => 'website users disabled',
		'stats_direct_mail' => 'Statistics for direct mail:',
		'stats_recalculate_stats' => 'Re-calculate cached statistics data',
		'stats_recalculate_cached_data' => 'Re-calculate Cached Data:',
		'nl_select_msg1' => 'There are no pages in the mail module.',
		'nl_select' => 'Select a newsletter',
		'nl_create' => 'Create a newsletter',
		'nl_create_msg1' => 'Click here to create a new page that you can later send as a direct mail.',
		'nl_info' => 'Newsletter info',
		'nl_viewPage' => 'View page',
		'nl_editPage' => 'Edit page',
		'nl_createDmailFromPage' => 'Create new direct mail based on this page',
		'nl_alreadyBasedOn' => 'These mails are already based on this page!',
		'nl_l_subject' => 'Subject',
		'nl_l_lastM' => 'Last mod.',
		'nl_l_sent' => 'Sent?',
		'nl_l_size' => 'Size',
		'nl_l_attach' => 'Attach.',
		'nl_l_type' => 'Type',
		'nl_l_tPage' => 'PAGE',
		'nl_l_tUrl' => 'EXT URL',
		'nl_l_column' => 'Column',
		'nl_l_ALL' => 'ALL',
		'nl_l_ONLY' => 'ONLY',
		'nl_l_update' => 'Update category settings',
		'nl_l_warning' => 'There are already %s Direct Mails based on this newsletter. Are you sure you want to create another one?',
		'nl_cat_msg1' => 'There are no content elements on the page.',
		'nl_cat' => 'Select categories',
		'nl_cat_msg2' => 'Setting categories for a content element means that the element will appear in the mail only if the recipient user has chosen that category in his profile.<br />If you do not set any category for an element, the element will appear in all mails.',
	),
	'dk' => Array (
	),
	'de' => Array (
		'dmail_noCreateAccess' => 'Sie besitzen nicht die Möglichkeit, versteckte oder zugriffsbeschränkte Seiten zu verschicken.',
		'dmail_noRegular' => 'Dieser Seitentyp kann nicht als E-Mail versendet werden. Bitte wählen Sie eine reguläre Seite.',
		'dmail_dovsk_selectDmail' => 'Auswahl des Versandobjektes',
		'dmail_dovsk_crFromNL' => 'Neuen Versand anhand eines Newsletters erstellen',
		'dmail_msg1_crFromNL' => 'Es gibt bisher keinen Newsletter, aus dem ein Versand erstellt worden ist.',
		'dmail_dovsk_crFromUrl' => 'Neuen Versand anhand einer externen URL erstellen',
		'dmail_createMail' => 'E-Mail erstellen',
		'dmail_view' => 'Versand',
		'dmail_noEdit_noPerms' => 'Kein Editieren möglich - Sie haben nicht die Berechtigung, Versandobjekte zu editieren.',
		'dmail_noEdit_isSent' => 'Kein Editieren möglich - E-Mail wurde bereits versandt.',
		'dmail_basedOn' => 'Der Versand basiert auf dieser Seite/diesem Newsletter.<br />Klicken Sie hier für mehr Informationen:',
		'dmail_menu_newsletters' => 'Newsletter',
		'dmail_menu_direct_mails' => 'Versand',
		'dmail_menu_quickMail' => 'QuickMail',
		'dmail_menu_list' => 'Empfängerliste',
		'dmail_menu_conf' => 'Modulkonfiguration',
		'dmail_menu_mailerengine' => 'Versand-Status',
		'dmail_menu_help' => 'Anleitung',
		'dmailer_mid' => 'Auftrags-Nr.:',
		'dmailer_job_begin' => 'Auftrag begonnen',
		'dmailer_job_end' => 'Auftrag beendet',
		'dmailer_invoked_at' => 'Aufgerufen: ',
		'dmailer_nothing_to_do' => 'Keine Aufträge.',
		'dmailer_ending' => 'Beendet, Laufzeit:',
		'dmailer_sys_dmail_record' => 'Inhalt der Tabelle sys_dmail',
		'dmailer_processed' => 'bearbeitet...',
		'dmail_menuItems' => '[Bitte auswählen]',
		'dmail_menuItems_prefetch' => 'Inhalt der E-Mail generieren (URL auslesen)',
		'dmail_menuItems_testmail' => 'Eine Testmail versenden',
		'dmail_menuItems_finalmail' => 'Massenversendung',
		'dmail_menuItems_stats' => 'Statistik dieser E-Mail',
		'dmail_menuItems_options' => 'Optionen:',
		'dmail_menuItems_note' => 'Hinweis:',
		'dmail_menuItems_note_use_menu' => 'Um den Inhalt für die E-Mail zu generieren, wählen Sie den entsprechenden Punkt unter Optionen aus.',
		'dmail_menuItems_note_enter_sender' => 'Sie haben noch nicht die E-Mail des Absenders angegeben!',
		'dmail_menuItems_note_send_test' => 'Über das Menü können Sie nun eine Test-Mail an eine von Ihnen festgelegte E-Mail-Adresse versenden oder eine Massenversendung an alle Empfänger anstoßen.',
		'dmail_back' => '< ZURÜCK',
		'dmail_yes' => 'JA',
		'dmail_no' => 'NEIN',
		'dmail_error' => 'FEHLER',
		'dmail_send' => 'Senden',
		'dmail_edit' => 'Ändern',
		'dmail_cancel' => 'Abbrechen',
		'dmail_number_records' => 'Anzahl der Einträge:',
		'dmail_subject' => 'Betreff:',
		'dmail_write_subject' => '[Betreff schreiben]',
		'dmail_HTML_url' => 'HTML URL:',
		'dmail_plaintext_url' => 'Plain Text URL:',
		'dmail_mailerengine_subject' => 'Betreff',
		'dmail_mailerengine_scheduled' => 'Planzeit',
		'dmail_mailerengine_delivery_begun' => 'Versand-Start',
		'dmail_mailerengine_delivery_ended' => 'Versand-Ende',
		'dmail_mailerengine_number_sent' => '# verschickt',
		'dmail_mailerengine_invoked' => 'Versand wurde angestoßen!',
		'dmail_mailerengine_status' => 'Status',
		'dmail_mailerengine_current_time' => 'Aktuelle Zeit:',
		'dmail_mailerengine_manual_invoke' => 'Manueller Versandstart',
		'dmail_mailerengine_manual_explain' => 'Falls Typo3 nicht so konfiguriert ist, um automatisch einen Versand anzustoßen, so haben Sie hier die Gelegenheit, dies manuell durchzuführen: ',
		'dmail_mailerengine_invoke_now' => 'Versand anstoßen',
		'dmail_mailerengine_log' => 'Protokoll:',
		'mailgroup_recip_from' => 'Empfänger der Gruppe:',
		'mailgroup_recip_number' => 'Anzahl der Empfänger:',
		'mailgroup_list_all' => 'Empfänger anzeigen',
		'mailgroup_table_address' => 'Tabelle: Address',
		'mailgroup_table_fe_users' => 'Tabelle: Website User',
		'mailgroup_plain_list' => 'Liste',
		'mailgroup_table_custom' => 'Benutzerdefinierte Tabelle',
		'mailgroup_download' => 'Download CSV-Datei',
		'mailgroup_import' => 'Import: CSV-Datei => \'ADDRESS\' - Tabelle',
		'mailgroup_import_rules' => 'Regeln:',
		'mailgroup_import_test' => 'Test-Import (es werden keine Daten gespeichert)',
		'mailgroup_import_now' => 'Jetzt importieren!',
		'recip_select_mailgroup' => 'Auswahl der Versandgruppe',
		'recip_create_mailgroup' => 'Neue Versandgruppe',
		'recip_create_mailgroup_msg' => 'Neue Versandgruppe erstellen?',
		'recip_import_mailgroup' => 'Importieren',
		'recip_import_mailgroup_msg' => 'Klicken Sie hier, um eine CSV-Datei einzulesen.',
		'prefetch_read_url' => 'Der Inhalt der E-Mail wird aus folgenden URLs ermittelt:',
		'prefetch_fetching' => 'Auslesen des Seiteninhaltes',
		'prefetch_patience' => 'Diese Aktion kann einige Zeit in Anspruch nehmen. Bitte haben Sie Geduld.',
		'prefetch_fetch' => 'Inhalt der E-Mail generieren',
		'prefetch_error_choose' => 'Sie müssen noch konfigurieren, wie Sie die E-Mail verschicken möchten: entweder HTML, plaintext oder HTML/plaintext. Im Moment ist keine von diesen Option ausgewählt!',
		'testmail_individual' => 'Individuelle Testmail',
		'testmail_individual_msg' => 'Bitte geben Sie den Empfänger für die Testmail an. Die hier generierte E-Mail wird auf dem Profil des ausgewählten Empfängers basieren.',
		'testmail_mailgroup' => 'Testmail an eine Versandgruppe',
		'testmail_mailgroup_msg' => 'Bitte geben Sie die Versandgruppe für die Testmail an. Die hier generierte E-Mail wird auf dem Profil der ausgewählten Versandgruppe basieren.',
		'testmail_simple' => 'Einfache Testmail versenden',
		'testmail_simple_msg' => 'Eine einfache Testmail enthält alle Elemente ohne Rücksicht auf die Kategorie. Jedoch werden keine Benutzerdaten ersetzt. Dies ist nur im personalisierten Massenversand möglich. Geben Sie hier den Empfänger für die Testmail an:',
		'send_sending' => 'Mail verschicken',
		'send_was_sent' => 'Die E-Mail wurde verschickt.',
		'send_was_sent_to_name' => 'Die E-Mail wurde an <strong>%s</strong> verschickt.',
		'send_was_sent_to_number' => 'Die E-Mail wurde an <strong>%s</strong> Empfänger verschickt.',
		'send_recipients' => 'Empfänger:',
		'send_was_scheduled' => 'Die E-Mail wurde für den Versand freigeben.',
		'send_was_scheduled_for' => 'Planversand der E-Mail:',
		'schedule_select_mailgroup' => 'Auswahl der Versandgruppe',
		'schedule_time' => 'Zeitpunkt des Versands (SS:MM TT-MM-YY):',
		'schedule_send_all' => 'An alle Empfänger der Versandgruppe versenden',
		'schedule_list_emails' => 'Mailversand - Liste der E-Mails',
		'schedule_enter_emails' => 'Geben Sie hier die E-Mail-Adressen der Empfänger an. Trennen Sie die Adressen mit Zeilenumbrüchen oder Kommata:',
		'quickmail_message' => 'Nachricht:',
		'quickmail_sender_name' => 'Absender (Name):',
		'quickmail_sender_email' => 'Absender (E-Mail):',
		'quickmail_one_mail_bcc' => 'Eine E-Mail an alle Empfänger über "Blind Carbon Copy" (Bcc)',
		'quickmail_one_mail_cc' => 'Eine E-Mail an alle Empfänger über "Carbon Copy" (Cc)',
		'quickmail_many_mails' => 'Für jeden Empfänger bitte einzelnd eine E-Mail versenden',
		'quickmail_send_now' => 'E-Mail an alle Mitglieder der auswählten Versandgruppe verschicken',
		'quickmail_break_lines' => 'Zeile nach 76 Buchstaben umbrechen:',
		'quickmail_missing_fields' => 'Bitte überprüfen Sie Ihre Formular-Eingaben.',
		'quickmail_sent_to' => 'Versendet an:',
		'quickmail_copy_to' => 'Kopie an:',
		'quickmail_mode' => 'Modus:',
		'quickmail_no_recipient' => 'Keine Empfänger.',
		'instructions_how' => 'Wie es funktioniert...',
		'instructions_text' => '
Mit Hilfe dieser Extension können Sie Typo3-Seiten als Newsletter an Personen aus einer Versandgruppe verschicken. 

Um einen Versand zu erstellen, müssen Sie folgende Schritte beachten:

<B>1)</B> Wählen Sie  \'Newsletter\' aus dem Menü oben aus.
    <B>2)</B> Erstellen Sie einen neuen \'Newsletter\'. Fügen Sie Inhalt hinzu, speichern Sie und schauen Sie sich die Vorschau an - es ist alles genauso, als ob Sie eine ganz reguläre Seite im Typo3 bearbeiten würden. Nur mit dem einzigsten Unterschied, dass diese Seite für den Versand bestimmt ist. 
    <B>3)</B> Wählen Sie nun Ihren Newsletter in der Liste aus. Nun sehen Sie Informationen betreffend dieser Seite und eine Aufzählung aller angelegten Content-Elemente. 
    <B>4)</B> Wenn Sie mit allem zufrieden sind und der Newsletter nun versendet werden soll, klicken Sie \'Versand dieser Seite erstellen\'. 
    <B>5)</B> Als Erstes muss der Inhalt der E-Mail generiert werden. Dazu wählen Sie unter OPTIONEN \'Inhalt der E-Mail generieren\' aus. 
    <B>6)</B> Vor einer Massenversendung sollten Sie unbedingt eine Testmail verschicken, damit Sie alle Links und Bilder nochmal überprüfen können. Auf jeden Fall sollten Sie URLs aus lokalen Netwerken 
    <B>7)</B> Wählen Sie \'Massenversendung\' aus, um den Newsletter zu verschicken. 
    
    <B>Der Unterschied zwischen einem Newsletter und einem Versand</B>
    Bei einem \'Newsletter\' handelt sich um eine reguläre Typo3-Seite. Mit dem Unterschied, dass sich diese unterhalb des Systemordners für Newsletter befindet. 
    EinA \'Versand\' ist ein Eintrag, der eine kompilierte Version des Newsletter oder der angegebenen externen URL enthält. 

    <B>Datenfelder beim Versand:</B>
    Personalisieren Sie Ihre Mails mit folgenden Zeichenfolgen:
    ###USER_uid### (ID des Empfängers)
    ###USER_name### (Vor- und Nachname)
    ###USER_firstname### (Vorname)
    ###USER_title###
    ###USER_email###
    ###USER_phone###
    ###USER_www###
    ###USER_address###
    ###USER_company###
    ###USER_city###
    ###USER_zip###
    ###USER_country###
    ###USER_fax###
    
    ###SYS_TABLE_NAME###
    ###SYS_MAIL_ID###
    ###SYS_AUTHCODE###
    
    (Die Felder ###USER_NAME### and ###USER_FIRSTNAME### stehen für großgeschriebene Versionen der passenden Felder)
',
		'stats_general_information' => 'Allgemeine Informationen:',
		'stats_total' => 'Insgesamt:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Plaintext:',
		'stats_mails_sent' => 'Verschickte E-Mails:',
		'stats_mails_returned' => 'Zurückgekommene E-Mails:',
		'stats_HTML_mails_viewed' => 'Gelesen (HTML-Mails):',
		'stats_unique_responses' => 'Angeklickte Links:',
		'stats_response' => 'Antworten:',
		'stats_total_responses' => 'Antworten insgesamt (Links):',
		'stats_links_clicked_per_respondent' => 'Links clicked per respondent:',
		'stats_count' => 'Anzahl:',
		'stats_total_mails_returned' => 'Insgesamt zurückgekommen:',
		'stats_recipient_unknown' => 'Unbekannte Empfänger:',
		'stats_mailbox_full' => 'Postfach voll:',
		'stats_bad_host' => 'Falscher Host:',
		'stats_error_in_header' => 'Fehler im Mail-Header:',
		'stats_reason_unkown' => 'Grund unbekannt:',
		'stats_list_returned' => 'Liste der zurückgekommenen Empfänger',
		'stats_disable_returned' => 'Deaktiverung der zurückgekommenen Empfänger',
		'stats_CSV_returned' => 'CSV-Export der zurückgekommenen Empfänger',
		'stats_emails_returned_list' => 'E-Mail-Adressen der zurückgekommenen Mails:',
		'stats_mails_returned_unknown_recipient' => 'Zurückgekommene E-Mails (Empfänger unbekannt):',
		'stats_list_returned_unknown_recipient' => 'Liste der zurückgekommenen E-Mails (Empfänger unbekannt)',
		'stats_disable_returned_unknown_recipient' => 'Zurückgekommene E-Mail-Adressen (Empfänger unbekannt) deaktivieren',
		'stats_CSV_returned_unknown_recipient' => 'CSV-Datei der zurückgekommenen E-Mails (Empfänger unbekannt)',
		'stats_emails_returned_unknown_recipient_list' => 'E-Mail-Adressen der zurückgekommen E-Mails (Empfänger unbekannt):',
		'stats_mails_returned_mailbox_full' => 'E-Mails zurückgekommen (Postfach voll):',
		'stats_list_returned_mailbox_full' => 'Liste der zurückgekommenen E-Mails (Postfach voll)',
		'stats_disable_returned_mailbox_full' => 'Zurückgekommene E-Mails (Postfach voll) deaktivieren',
		'stats_CSV_returned_mailbox_full' => 'CSV-Datei der zurückgekommenen E-Mails (Postfach voll)',
		'stats_emails_returned_mailbox_full_list' => 'E-Mail-Adressen der zurückgekommen E-Mails (Postfach voll):',
		'stats_mails_returned_bad_host' => 'E-Mails zurückgekommen (Unbekannter Server):',
		'stats_list_returned_bad_host' => 'Liste der zurückgekommenen E-Mails (Unbekannter Server)',
		'stats_disable_returned_bad_host' => 'Zurückgekommene E-Mails (Unbekannter Server) deaktivieren',
		'stats_CSV_returned_bad_host' => 'CSV-Datei der zurückgekommenen E-Mails (Unbekannter Server)',
		'stats_emails_returned_bad_host_list' => 'E-Mail-Adressen der zurückgekommen E-Mails (Unbekannter Server):',
		'stats_mails_returned_bad_header' => 'E-Mails zurückgekommen (Fehler in Kopfzeile):',
		'stats_list_returned_bad_header' => 'Liste der zurückgekommenen E-Mails (Fehler in Kopfzeile)',
		'stats_disable_returned_bad_header' => 'Zurückgekommene E-Mails (Fehler in Kopfzeile) deaktivieren',
		'stats_CSV_returned_bad_header' => 'CSV-Datei der zurückgekommenen E-Mails (Fehler in Kopfzeile)',
		'stats_emails_returned_bad_header_list' => 'E-Mail-Adressen der zurückgekommen E-Mails (Fehler in Kopfzeile):',
		'stats_mails_returned_reason_unknown' => 'E-Mails zurückgekommen (unbekannter Grund):',
		'stats_list_returned_reason_unknown' => 'Liste der zurückgekommenen E-Mails (unbekannter Grund)',
		'stats_disable_returned_reason_unknown' => 'Zurückgekommene E-Mails (unbekannter Grund) deaktivieren',
		'stats_CSV_returned_reason_unknown' => 'CSV-Datei der zurückgekommenen E-Mails (unbekannter Grund)',
		'stats_emails_returned_reason_unknown_list' => 'E-Mail-Adressen der zurückgekommen E-Mails (unbekannter Grund):',
		'stats_emails_disabled' => 'Adressen deaktiviert',
		'stats_website_users_disabled' => 'Website-Benutzer deaktiviert',
		'stats_direct_mail' => 'Versand-Statistik:',
		'stats_recalculate_stats' => 'Neuberechnung der Daten aus dem Zwischenspeicher (Cache)',
		'stats_recalculate_cached_data' => 'Neuberechnung der Daten aus dem Zwischenspeicher (Cache):',
		'nl_select_msg1' => 'Es gibt keine Seiten für diese Extension.',
		'nl_select' => 'Newsletter auswählen',
		'nl_create' => 'Newsletter erstellen',
		'nl_create_msg1' => 'Klicken Sie hier, um eine neue Typo3-Seite, die Sie später als Newsletter verschicken können, anzulegen.',
		'nl_info' => 'Newsletter-Info',
		'nl_viewPage' => 'Seite anzeigen',
		'nl_editPage' => 'Seite ändern',
		'nl_createDmailFromPage' => 'Versand dieser Seite erstellen',
		'nl_alreadyBasedOn' => 'Diese Versandobjekte basieren bereits auf der ausgewählten Seite!',
		'nl_l_subject' => 'Betreff',
		'nl_l_lastM' => 'Letzte Änderung:',
		'nl_l_sent' => 'Verschickt?',
		'nl_l_size' => 'Größe',
		'nl_l_attach' => 'Anhang',
		'nl_l_type' => 'Typ',
		'nl_l_tPage' => 'SEITE',
		'nl_l_tUrl' => 'Externe URL',
		'nl_l_column' => 'Spalte',
		'nl_l_ALL' => 'ALLE',
		'nl_l_ONLY' => 'NUR',
		'nl_l_update' => 'Kategorie-Einstellungen ändern',
		'nl_l_warning' => 'Für diesen Newsletter wurden bereits %s Versandobjekte erstellt. Sind Sie sicher, dass Sie einen weiteren Versand erstellen möchten?',
		'nl_cat_msg1' => 'Es wurden keine Seiteninhalte auf der Seite gefunden.',
		'nl_cat' => 'Ausschluss von Seiteninhalten anhand von Kategorien',
		'nl_cat_msg2' => 'Das Setzen einer Kategorie für bestimmte Seiteninhalte bedeutet, dass nur Empfänger, die dieser Kategorie angehören, den Seiteninhalt auch tatsächlich bekommen.',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'dmail_folders' => 'Dossiers d\'Envoi ciblé disponibles',
		'dmail_noCreateAccess' => 'Vous ne pouvez pas envoyer des pages cachées ou à accès restreint.',
		'dmail_noRegular' => 'Ce type de page ne peut pas être envoyé comme message de courrier. Veuillez choisir une page ordinaire.',
		'dmail_dovsk_selectDmail' => 'Choisissez un bulletin',
		'dmail_dovsk_crFromNL' => 'Créer un nouveau bulletin basé sur une page',
		'dmail_msg1_crFromNL' => 'Il n\'y a aucune page qui ne soit déjà un bulletin!',
		'dmail_dovsk_crFromUrl' => 'Créer un bulletin basé sur un URL externe',
		'dmail_createMail' => 'Créer un bulletin',
		'dmail_view' => 'Voir le bulletin',
		'dmail_noEdit_noPerms' => 'Vous n\'avez pas la permission d\'éditer les bulletins.',
		'dmail_noEdit_isSent' => 'Vous ne pouvez éditer ce bulletin car il est déjà envoyé.',
		'dmail_basedOn' => 'Le bulletin est basé sur cette page.<br />Cliquez ici pour voir l\'information sur la page:',
		'dmail_menu_newsletters' => 'Pages',
		'dmail_menu_direct_mails' => 'Bulletins',
		'dmail_menu_quickMail' => 'Courrier rapide',
		'dmail_menu_list' => 'Listes de distribution',
		'dmail_menu_conf' => 'Configuration du module',
		'dmail_menu_mailerengine' => 'État des envois massifs',
		'dmail_menu_help' => 'Instructions',
		'dmail_menu_convert_categories' => 'Conversion des catégories',
		'dmailer_mid' => 'Envoi numero:',
		'dmailer_job_begin' => 'Début de l\'envoi',
		'dmailer_job_end' => 'Fin de l\'envoi',
		'dmailer_invoked_at' => 'Envoi demandé à',
		'dmailer_nothing_to_do' => 'Rien à envoyer.',
		'dmailer_ending' => 'Terminé avec durée de traitement de',
		'dmailer_sys_dmail_record' => 'Enregistrement sys_dmail',
		'dmailer_processed' => 'traité...',
		'dmail_menuItems' => '[MENU]',
		'dmail_menuItems_prefetch' => 'Préparer le bulletin pour l\'envoi massif',
		'dmail_menuItems_testmail' => 'Envoyer un message d\'essai',
		'dmail_menuItems_finalmail' => 'Déclencher l\'envoi massif',
		'dmail_menuItems_stats' => 'Afficher les statistiques de l\'envoi massif',
		'dmail_menuItems_options' => 'Options:',
		'dmail_menuItems_note' => 'Note:',
		'dmail_menuItems_note_use_menu' => 'Utilisez le menu pour préparer le bulletin pour l\'envoi massif',
		'dmail_menuItems_note_enter_sender' => 'Vous devez spécifier une adresse d\'expéditeur pour ce bulletin!',
		'dmail_menuItems_note_send_test' => 'Utilisez le menu pour envoyer un message d\'essai ou déclencher l\'envoi à tous les destinataires.',
		'dmail_back' => '< Retour',
		'dmail_yes' => 'OUI',
		'dmail_no' => 'NON',
		'dmail_error' => 'ERREUR',
		'dmail_send' => 'Envoyer',
		'dmail_edit' => 'Éditer',
		'dmail_cancel' => 'Annuler',
		'dmail_number_records' => 'Nombre d\'enregistrements:',
		'dmail_subject' => 'Sujet:',
		'dmail_write_subject' => '[insérez ici le sujet]',
		'dmail_HTML_url' => 'URL du contenu HTML:',
		'dmail_plaintext_url' => 'URL du texte simple:',
		'dmail_mailerengine_subject' => 'Sujet',
		'dmail_mailerengine_scheduled' => 'Envoi déclenché',
		'dmail_mailerengine_delivery_begun' => 'Envoi initié',
		'dmail_mailerengine_delivery_ended' => 'Envoi complété',
		'dmail_mailerengine_number_sent' => '# envoyés',
		'dmail_mailerengine_invoked' => 'Envoi déclenché!',
		'dmail_mailerengine_status' => 'État des envois massifs',
		'dmail_mailerengine_current_time' => 'Heure présente:',
		'dmail_mailerengine_manual_invoke' => 'Déclencher les envois manuellement',
		'dmail_mailerengine_manual_explain' => 'Si Typo3 n\'est pas configuré pour inicier les envois automatiquement, vous pouvez les inicier en cliquant ici:',
		'dmail_mailerengine_invoke_now' => 'Déclencher les envois',
		'dmail_mailerengine_log' => 'Journal:',
		'mailgroup_recip_from' => 'Destinataires de la liste de distribution:',
		'mailgroup_recip_number' => 'Nombre de destinataires:',
		'mailgroup_list_all' => 'Lister tous les destinataires',
		'mailgroup_table_address' => 'Table des adresses',
		'mailgroup_table_fe_users' => 'Table des utilisateurs du site',
		'mailgroup_plain_list' => 'Liste simple',
		'mailgroup_table_custom' => 'Table sur mesure',
		'mailgroup_download' => 'Télécharcher dans un fichier de format CSV',
		'mailgroup_import' => 'Importer une liste de format CSV dans la table des adresses',
		'mailgroup_import_rules' => 'Règles:',
		'mailgroup_import_test' => 'Essai d\'importation sans écriture',
		'mailgroup_import_now' => 'Importer maintenant!',
		'recip_select_mailgroup' => 'Choisissez une liste de distribution',
		'recip_create_mailgroup' => 'Nouvelle liste de distribution',
		'recip_create_mailgroup_msg' => 'Cliquez ici pour créer une nouvelle liste de distribution',
		'recip_import_mailgroup' => 'Importer une liste de distribution',
		'recip_import_mailgroup_msg' => 'Cliquez ici pour importer une liste de format CSV',
		'prefetch_read_url' => 'Le bulletin sera preparé pour envoi massif en utilisant le contenu des adresses URL suivantes:',
		'prefetch_fetching' => 'Préparation du bulletin en vue de l\'envoi massif',
		'prefetch_patience' => 'Cette opération peut demander quelques minutes de patience.',
		'prefetch_fetch' => 'Préparer le bulletin',
		'prefetch_error_choose' => 'Vous devez choisir d\'envoyer un contenu HTML, de texte simple ou les deux. En ce moment, rien n\'a été choisi.',
		'testmail_individual' => 'Message d\'essai - Individuel',
		'testmail_individual_msg' => 'Choisissez le destinataire du message d\'essai. Le message sera créé selon le profil du destinataire choisi.',
		'testmail_mailgroup' => 'Message d\'essai - Liste de distribution',
		'testmail_mailgroup_msg' => 'Choisissez la liste de distribution du message d\'essai. Les messages seront créés selon le profil de chacun des membres de la liste de distribution choisie.',
		'testmail_simple' => 'Message d\'essai - Simple',
		'testmail_simple_msg' => 'Un message d\'essai simple inclut tous les éléments de contenu de toutes catégories, mais les valeurs des champs de type USER_champ ne sont pas substituées. Écrivez une adresse de courrier électronique destinataire pour le message d\'essai:',
		'send_sending' => 'Envoi des messages',
		'send_was_sent' => 'Le message a été envoyé.',
		'send_was_sent_to_name' => 'Le message a été envoyé à <strong>%s</strong>.',
		'send_was_sent_to_number' => 'Le message a été envoyé à <strong>%s</strong> destinataires.',
		'send_recipients' => 'Destinataires:',
		'send_was_scheduled' => 'Envoi du message programmé',
		'send_was_scheduled_for' => 'L\'envoi du bulletin a été programmé pour',
		'schedule_select_mailgroup' => 'Choisissez une liste de distribution',
		'schedule_time' => 'Heure d\'envoi (hh:mm jj-mm-aa):',
		'schedule_send_all' => 'Envoyer à tous les membres de la liste de distribution',
		'schedule_list_emails' => 'Envoi du message à une liste d\'adresses',
		'schedule_enter_emails' => 'Écrivez les adresses des destinataires, une par ligne ou séparées par des virgules ",":',
		'quickmail_message' => 'Message:',
		'quickmail_sender_name' => 'Nom de l\'expéditeur:',
		'quickmail_sender_email' => 'Adresse de l\'expéditeur:',
		'quickmail_one_mail_bcc' => 'Un seul message avec copie cachée à tous les destinataires (Bcc)',
		'quickmail_one_mail_cc' => 'Un seul message avec copie à tous les destinataires (Cc)',
		'quickmail_many_mails' => 'Plusieurs messages, un par destinataire',
		'quickmail_send_now' => 'Envoyer le message à tous les destinataires maintenant!',
		'quickmail_break_lines' => 'Bris de ligne à 76 caractères:',
		'quickmail_missing_fields' => 'Vous n\'avez pas complété tous les champs correctement!',
		'quickmail_sent_to' => 'Envoyé à:',
		'quickmail_copy_to' => 'Copie à:',
		'quickmail_mode' => 'Mode:',
		'quickmail_no_recipient' => 'Aucun destinataire.',
		'configure_direct_mail_module' => 'Configuration du module d\'envoi massif de courrier',
		'stats_general_information' => 'Statistiques générales:',
		'stats_total' => 'Total:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Texte simple:',
		'stats_mails_sent' => 'Messages envoyés',
		'stats_mails_returned' => 'Messages retournés:',
		'stats_HTML_mails_viewed' => 'Messages HTML visionnés:',
		'stats_unique_responses' => 'Réponses distinctes (lien cliqué):',
		'stats_response' => 'Réponses:',
		'stats_total_responses' => 'Réponses totales (link click):',
		'stats_links_clicked_per_respondent' => 'Liens cliqués/répondant:',
		'stats_count' => 'Nombre:',
		'stats_total_mails_returned' => 'Messages retournés:',
		'stats_recipient_unknown' => 'Destinataire inconnu:',
		'stats_mailbox_full' => 'Boîte postale pleine:',
		'stats_bad_host' => 'Hôte inconnu:',
		'stats_error_in_header' => 'Erreur d\'entête:',
		'stats_reason_unkown' => 'Raison inconnue:',
		'stats_list_returned' => 'Lister les adresses des messages retournés',
		'stats_disable_returned' => 'Désactiver  les adresses des messages retournés',
		'stats_CSV_returned' => 'CSV des adresses des messages retournés',
		'stats_emails_returned_list' => 'Adresses des messages retournés:',
		'stats_mails_returned_unknown_recipient' => 'Messages retournés avec destinataire inconnu:',
		'stats_list_returned_unknown_recipient' => 'Lister les adresses des messages retournés avec destinataire inconnu',
		'stats_disable_returned_unknown_recipient' => 'Désactiver  les adresses des messages retournés avec destinataire inconnu',
		'stats_CSV_returned_unknown_recipient' => 'CSV des adresses des messages retournés avec destinataire inconnu',
		'stats_emails_returned_unknown_recipient_list' => 'Adresses des messages retournés avec destinataire inconnu:',
		'stats_mails_returned_mailbox_full' => 'Messages retournés avec boîte postale pleine:',
		'stats_list_returned_mailbox_full' => 'Lister les adresses des messages retournés avec boîte postale pleine',
		'stats_disable_returned_mailbox_full' => 'Désactiver  les adresses des messages retournés avec boîte postale pleine',
		'stats_CSV_returned_mailbox_full' => 'CSV des adresses des messages retournés avec boîte postale pleine',
		'stats_emails_returned_mailbox_full_list' => 'Adresses des messages retournés avec boîte postale pleine:',
		'stats_mails_returned_bad_host' => 'Messages retournés avec hôte inconnu:',
		'stats_list_returned_bad_host' => 'Lister les adresses des messages retournés avec hôte inconnu',
		'stats_disable_returned_bad_host' => 'Désactiver  les adresses des messages retournés avec hôte inconnu',
		'stats_CSV_returned_bad_host' => 'CSV des adresses des messages retournés avec hôte inconnu',
		'stats_emails_returned_bad_host_list' => 'Adresses des messages retournés avec hôte inconnu:',
		'stats_mails_returned_bad_header' => 'Messages retournés avec erreur d\'entête:',
		'stats_list_returned_bad_header' => 'Lister les adresses des messages retournés avec erreur d\'entête',
		'stats_disable_returned_bad_header' => 'Désactiver  les adresses des messages retournés avec erreur d\'entête',
		'stats_CSV_returned_bad_header' => 'CSV des adresses des messages retournés avec erreur d\'entête',
		'stats_emails_returned_bad_header_list' => 'Adresses des messages retournés avec erreur d\'entête:',
		'stats_mails_returned_reason_unknown' => 'Messages retournés pour raison inconnue:',
		'stats_list_returned_reason_unknown' => 'Lister les adresses des messages retournés pour raison inconnue',
		'stats_disable_returned_reason_unknown' => 'Désactiver  les adresses des messages retournés pour raison inconnue',
		'stats_CSV_returned_reason_unknown' => 'CSV des adresses des messages retournés pour raison inconnue',
		'stats_emails_returned_reason_unknown_list' => 'Adresses des messages retournés pour raison inconnue:',
		'stats_emails_disabled' => 'adresses désactivées',
		'stats_website_users_disabled' => 'usagers du site désactivés',
		'stats_direct_mail' => 'Statistiques d\'envoi massif:',
		'stats_recalculate_stats' => 'Recalculer les données statistiques en cache',
		'stats_recalculate_cached_data' => 'Recalculer les données en cache:',
		'nl_select_msg1' => 'Il n\'y a aucune page dans le dossier d\'envoi massif.',
		'nl_select' => 'Choisissez une page existante',
		'nl_create' => 'Créez une nouvelle page',
		'nl_create_msg1' => 'Cliquez ici pour créer une nouvelle page qui pourra être envoyée comme bulletin.',
		'nl_info' => 'Information sur la page',
		'nl_viewPage' => 'Voir la page',
		'nl_editPage' => 'Éditer la page',
		'nl_createDmailFromPage' => 'Créer un bulletin basé sur cette page',
		'nl_alreadyBasedOn' => 'Ces bulletins sont déjà basés sur cette page',
		'nl_l_subject' => 'Sujet',
		'nl_l_lastM' => 'Dernier changement',
		'nl_l_sent' => 'Envoi déclenché?',
		'nl_l_size' => 'Grosseur',
		'nl_l_attach' => 'Documents joints',
		'nl_l_type' => 'Type',
		'nl_l_tPage' => 'PAGE',
		'nl_l_tUrl' => 'URL Externe',
		'nl_l_column' => 'Colonne',
		'nl_l_ALL' => 'TOUT',
		'nl_l_ONLY' => 'SEULEMENT',
		'nl_l_update' => 'Mettre à jour les catégories du bulletin',
		'nl_l_warning' => 'Il existe déjà %s bulletin(s) basé(s) sur cette page. Êtes-vous certain de vouloir en créer un autre?',
		'nl_cat_msg1' => 'La page ne contient aucun élément de contenu.',
		'nl_cat' => 'Choisir les catégories',
		'nl_cat_msg2' => 'Choisir les catégories d\'un élément de contenu signifie que cet élément apparaîtra dans le bulletin seulement lorsque le destinataire aura inclus cette catégorie dans son profil.<br /><br />Si vous ne choisissez aucune catégorie, l\'élément apparaîtra dans tous les bulletins.',
	),
	'es' => Array (
		'dmail_noCreateAccess' => 'No puede enviar páginas escondidas o de acceso restricto.',
		'dmail_noRegular' => 'Este typo de página no se puede enviar como boletín. Favor de eligir una página normal.',
		'dmail_dovsk_selectDmail' => 'Elegir boletín',
		'dmail_dovsk_crFromNL' => 'Crear un boletín basado en una página',
		'dmail_msg1_crFromNL' => 'No hay página que no está ya un boletín!',
		'dmail_dovsk_crFromUrl' => 'Crear un nuevo boletín basado en un URL externo',
		'dmail_createMail' => 'Crear boletín',
		'dmail_view' => 'Información sobre el boletín',
		'dmail_noEdit_noPerms' => 'No se puede editar. No tiene permiso para editar boletínes.',
		'dmail_noEdit_isSent' => 'No se puede editar. ¡Boletín ya enviado!',
		'dmail_basedOn' => 'Este boletín es basado en esta página.<BR>Pulse aquí para ver la información sobre esta página:',
		'dmail_menu_newsletters' => 'Páginas',
		'dmail_menu_direct_mails' => 'Boletines',
		'dmail_menu_quickMail' => 'Correo rápido',
		'dmail_menu_list' => 'Listas de correo',
		'dmail_menu_conf' => 'Configuración del módulo',
		'dmail_menu_mailerengine' => 'Estado de los envíos masivos',
		'dmail_menu_help' => 'Instrucciones',
		'dmailer_mid' => 'Envío número:',
		'dmailer_job_begin' => 'Inicio del envío',
		'dmailer_job_end' => 'Final del envío',
		'dmailer_invoked_at' => 'Envío requerido a las',
		'dmailer_nothing_to_do' => 'Nada que hacer.',
		'dmailer_ending' => 'Terminando con duración de procesamiento:',
		'dmailer_sys_dmail_record' => 'Registro sys_dmail',
		'dmailer_processed' => 'procesado...',
		'dmail_menuItems' => '[MENÚ]',
		'dmail_menuItems_prefetch' => 'Preparar el boletín para el envío masivo',
		'dmail_menuItems_testmail' => 'Enviar un correo de prueba',
		'dmail_menuItems_finalmail' => 'Requerer el envío masivo',
		'dmail_menuItems_stats' => 'Ver las estadísticas del envío masivo',
		'dmail_menuItems_options' => 'Opciones:',
		'dmail_menuItems_note' => 'Nota:',
		'dmail_menuItems_note_use_menu' => 'Utilice el menú para preparar el boletín para el envío masivo',
		'dmail_menuItems_note_enter_sender' => 'Tiene que introducir un remitente de correo para este boletín!',
		'dmail_menuItems_note_send_test' => 'Utilice el menú para enviar un correo de prueba o para requerer el envío a todos los destinatarios.',
		'dmail_back' => '< Regresar',
		'dmail_yes' => 'SÍ',
		'dmail_no' => 'NO',
		'dmail_error' => 'ERROR',
		'dmail_send' => 'Enviar',
		'dmail_edit' => 'Editar',
		'dmail_cancel' => 'Anular',
		'dmail_number_records' => 'Número de registros:',
		'dmail_subject' => 'Asunto:',
		'dmail_write_subject' => '[introducir aquí el asunto]',
		'dmail_HTML_url' => 'URL del contenido HTML:',
		'dmail_plaintext_url' => 'URL del texto simple:',
		'dmail_mailerengine_subject' => 'Asunto',
		'dmail_mailerengine_scheduled' => 'Envío requerido',
		'dmail_mailerengine_delivery_begun' => 'Envío iniciado',
		'dmail_mailerengine_delivery_ended' => 'Envío completado',
		'dmail_mailerengine_number_sent' => '# enviados',
		'dmail_mailerengine_invoked' => 'Envío requerido!',
		'dmail_mailerengine_status' => 'Estado de los envíos masivos',
		'dmail_mailerengine_current_time' => 'Ahora son las:',
		'dmail_mailerengine_manual_invoke' => 'Iniciar los envíos a mano',
		'dmail_mailerengine_manual_explain' => 'Si Typo3 no es configurado para iniciar los envíos automaticamente, puede iniciarlos pulsando aquí:',
		'dmail_mailerengine_invoke_now' => 'Iniciar los envíos',
		'dmail_mailerengine_log' => 'Bitácora:',
		'mailgroup_recip_from' => 'Destinatarios de la lista de correo:',
		'mailgroup_recip_number' => 'Número de destinatarios:',
		'mailgroup_list_all' => 'Alistar todos los destinatarios',
		'mailgroup_table_address' => 'Tabla de las direcciones',
		'mailgroup_table_fe_users' => 'Tabla de los usuarios del sitio',
		'mailgroup_plain_list' => 'Lista simple',
		'mailgroup_table_custom' => 'Tabla',
		'mailgroup_download' => 'Descargar en archivo de formato CSV',
		'mailgroup_import' => 'Importar lista de formato CSV hacía la tabla de las direcciones',
		'mailgroup_import_rules' => 'Reglas:',
		'mailgroup_import_test' => 'Prueba de importación sín escribir',
		'mailgroup_import_now' => '¡Importar ahora mismo!',
		'recip_select_mailgroup' => 'Elija una lista de correo',
		'recip_create_mailgroup' => 'Nueva lista de correo',
		'recip_create_mailgroup_msg' => 'Pulsa aquí para crear nueva lista de correo',
		'recip_import_mailgroup' => 'Importar lista de correo',
		'recip_import_mailgroup_msg' => 'Pulsa aquí para importar una lista de formato CSV',
		'prefetch_read_url' => 'El boletín será preparado para el envío utilizando el contenido de las direcciones URL siguientes:',
		'prefetch_fetching' => 'Preparando el boletín para el envío masivo',
		'prefetch_patience' => 'Esta operación puede requerer algunos minutos de paciencia.',
		'prefetch_fetch' => 'Preparar el boletín',
		'prefetch_error_choose' => 'Tiene que elegir de enviar contenido HTML, de texto simple o ambos. En este momento, nada está electo.',
		'testmail_individual' => 'Correo de prueba - Individual',
		'testmail_individual_msg' => 'Elija un destinatario para este correo de prueba. El correo será creado según el perfil de este destinatario.',
		'testmail_mailgroup' => 'Correo de prueba - Lista de correo',
		'testmail_mailgroup_msg' => 'Elija una lista de correo para este correo de prueba. Los correos serán creados según el perfil de cada uno de los miembros de esta lista de correo.',
		'testmail_simple' => 'Correo de prueba - Simple',
		'testmail_simple_msg' => 'Un correo de prueba simple incluye todos los elementos de contenido de todas categorías, pero las valores de los campos de tipo USER_campo no son substituidas. Introduzca una dirección de correo para el correo de prueba:',
		'send_sending' => 'Enviando correos',
		'send_was_sent' => 'El correo fue enviado.',
		'send_was_sent_to_name' => 'El correo fue enviado a <strong>%s</strong>.',
		'send_was_sent_to_number' => 'El correo fue enviado a <strong>%s</strong> destinatarios.',
		'send_recipients' => 'Destinatarios:',
		'send_was_scheduled' => 'Envío del boletín programado',
		'send_was_scheduled_for' => 'El envío del boletín fue programado para las',
		'schedule_select_mailgroup' => 'Elija una lista de correo',
		'schedule_time' => 'Hora de envío (hh:mm dd-mm-aa):',
		'schedule_send_all' => 'Enviar a todos los miembros de la lista de correo',
		'schedule_list_emails' => 'Envío del correo a una lista de direcciones',
		'schedule_enter_emails' => 'Introduzca las direcciones de los destinarios separándolas mediante fin de linéa o coma ",":',
		'quickmail_message' => 'Mensaje:',
		'quickmail_sender_name' => 'Nombre del remitente:',
		'quickmail_sender_email' => 'Dirección del remitente:',
		'quickmail_one_mail_bcc' => 'Un mensaje único con copia carbón oculta a todos los destinatarios (Bcc)',
		'quickmail_one_mail_cc' => 'Un mensaje único con copia carbón a todos los destinatarios (Cc)',
		'quickmail_many_mails' => 'Mensajes múltiples, uno por destinatario',
		'quickmail_send_now' => 'Enviar mensaje a todos los destinatarios ahora mismo!',
		'quickmail_break_lines' => 'Cambio de línea a 76 carácteres:',
		'quickmail_missing_fields' => 'No ha introducido todos los campos correctamente!',
		'quickmail_sent_to' => 'Enviado a:',
		'quickmail_copy_to' => 'Copia carbón a:',
		'quickmail_mode' => 'Modo:',
		'quickmail_no_recipient' => 'Ningún destinatario.',
		'configure_direct_mail_module' => 'Configuración del módulo de correo masivo',
		'instructions_how' => '¿Qué hacer?',
		'instructions_text' => '
	Mediante este módulo puede crear páginas que luego puede enviar como boletines por correo electrónico a las direcciones suscritas o incluidas en listas de correo.
	
	Para crear y enviar un boletín, siga los pasos siguientes:
	<B>1)</b> Elija \'Páginas\' en el menú arriba.
	<B>2)</b> Elija une página ya creada o cree una nueva página. Inciera contenido en la página nueva y guárdela de la misma manera que páginas regulares.
	<B>3)</b> Pulse en su página en la lista de páginas: puede ver la información sobre esta página. Nota: En La Matatena, A.C., no utilizamos las categorías de contenido.
	<B>4)</b> Cuando la página esta lista, pulse en el vínculo \'Crear un nuevo boletín basado en esta página\'.
	<B>5)</b> En el menú bajo las informaciones del boletín, elija la opción \'Preparar el boletín para el envío masivo\' e siga las instrucciones en la página que aparece.
	<B>6)</b> En el menú bajo las informaciones del boletín, elija la opción \'Enviar un correo de prueba\'. Es muy importante enviar un correo de prueba y comprobar que todos los vínculos del mensaje son correctos antes del envío del boletín a todos los suscriptores. 
	<B>7)</b> Cuando el correo de prueba es correcto, elija en el menú bajo las informaciones del boletín la opción \'Requerer el envío masivo\'.
	<B>8)</b> Elija \'Estado de los envíos masivos\' en el menú arriba para comprobar el estado de su envío. Es posible que sea necesario pulsar en el botón \'Iniciar los envíos\' para iniciar el envío de su boletín.
',
		'stats_general_information' => 'Estadísticas generales:',
		'stats_total' => 'Total:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Texto simple:',
		'stats_mails_sent' => 'Correos enviados:',
		'stats_mails_returned' => 'Correos regresados:',
		'stats_HTML_mails_viewed' => 'Correos HTML vistos:',
		'stats_unique_responses' => 'Respuestas distintas (vínculo pulsado):',
		'stats_response' => 'Respuestas:',
		'stats_total_responses' => 'Respuestas totales (link click):',
		'stats_links_clicked_per_respondent' => 'Vínculos pulsados/respondiente:',
		'stats_count' => 'Número:',
		'stats_total_mails_returned' => 'Correos regresados:',
		'stats_recipient_unknown' => 'Destinatario desconocido:',
		'stats_mailbox_full' => 'Buzón lleno:',
		'stats_bad_host' => 'Huésped desconocido:',
		'stats_error_in_header' => 'Encabezado erroneo:',
		'stats_reason_unkown' => 'Razón desconocida:',
		'stats_list_returned' => 'Alistar las direcciones de los correos regresados',
		'stats_disable_returned' => 'Deshabilitar las direcciones de los correos regresados',
		'stats_CSV_returned' => 'CSV de las direcciones de los correos regresados',
		'stats_emails_returned_list' => 'Direcciones de los correos regresados:',
		'stats_mails_returned_unknown_recipient' => 'Correos regresados con destinatario desconocido:',
		'stats_list_returned_unknown_recipient' => 'Alistar las direcciones de los correos regresados con destinatario desconocido',
		'stats_disable_returned_unknown_recipient' => 'Deshabilitar las direcciones de los correos regresados con destinatario desconocido',
		'stats_CSV_returned_unknown_recipient' => 'CSV de las direcciones de los correos regresados con destinatario desconocido',
		'stats_emails_returned_unknown_recipient_list' => 'Direcciones de los correos regresados con destinatario desconocido:',
		'stats_mails_returned_mailbox_full' => 'Correos regresados con buzón lleno:',
		'stats_list_returned_mailbox_full' => 'Alistar las direcciones de los correos regresados con buzón lleno',
		'stats_disable_returned_mailbox_full' => 'Deshabilitar las direcciones de los correos regresados con buzón lleno',
		'stats_CSV_returned_mailbox_full' => 'CSV de las direcciones de los correos regresados con buzón lleno',
		'stats_emails_returned_mailbox_full_list' => 'Direcciones de los correos regresados con buzón lleno:',
		'stats_mails_returned_bad_host' => 'Correos regresados con huésped desconocido:',
		'stats_list_returned_bad_host' => 'Alistar las direcciones de los correos regresados con huésped desconocido',
		'stats_disable_returned_bad_host' => 'Deshabilitar las direcciones de los correos regresados con huésped desconocido',
		'stats_CSV_returned_bad_host' => 'CSV de las direcciones de los correos regresados con huésped desconocido',
		'stats_emails_returned_bad_host_list' => 'Direcciones de los correos regresados con huésped desconocido:',
		'stats_mails_returned_bad_header' => 'Correos regresados con encabezado erroneo:',
		'stats_list_returned_bad_header' => 'Alistar las direcciones de los correos regresados con encabezado erroneo',
		'stats_disable_returned_bad_header' => 'Deshabilitar las direcciones de los correos regresados con encabezado erroneo',
		'stats_CSV_returned_bad_header' => 'CSV de las direcciones de los correos regresados con encabezado erroneo',
		'stats_emails_returned_bad_header_list' => 'Direcciones de los correos regresados con encabezado erroneo:',
		'stats_mails_returned_reason_unknown' => 'Correos regresados por razón desconocida:',
		'stats_list_returned_reason_unknown' => 'Alistar las direcciones de los correos regresados por razón desconocida',
		'stats_disable_returned_reason_unknown' => 'Deshabilitar las direcciones de los correos regresados por razón desconocida',
		'stats_CSV_returned_reason_unknown' => 'CSV de las direcciones de los correos regresados por razón desconocida',
		'stats_emails_returned_reason_unknown_list' => 'Direcciones de los correos regresados por razón desconocida:',
		'stats_emails_disabled' => 'direcciones deshabilitadas',
		'stats_website_users_disabled' => 'usuarios del sitio deshabilitados',
		'stats_direct_mail' => 'Estadísticas de envío masivo:',
		'stats_recalculate_stats' => 'Volver a calcular las estadísticas en el cache',
		'stats_recalculate_cached_data' => 'Volver a calcular los datos estadísticos en el cache:',
		'nl_select_msg1' => 'No hay páginas en la carpeta de difusión.',
		'nl_select' => 'Elija una página existente',
		'nl_create' => 'Crea una página nueva',
		'nl_create_msg1' => 'Pulse aquí para crear una nueva página que luego se puede enviar como boletín.',
		'nl_info' => 'Información sobre la página',
		'nl_viewPage' => 'Ver la página',
		'nl_editPage' => 'Editar la página',
		'nl_createDmailFromPage' => 'Crear un boletín basado en esta página',
		'nl_alreadyBasedOn' => 'Estos boletines ya son basados en esta página',
		'nl_l_subject' => 'Asunto',
		'nl_l_lastM' => 'Último cambio',
		'nl_l_sent' => '¿Envío requerido?',
		'nl_l_size' => 'Tamaño',
		'nl_l_attach' => 'Archivos adjuntos',
		'nl_l_type' => 'Tipo',
		'nl_l_tPage' => 'PÁGINA',
		'nl_l_tUrl' => 'URL externo',
		'nl_l_column' => 'Columna',
		'nl_l_ALL' => 'TODO',
		'nl_l_ONLY' => 'SÓLO',
		'nl_l_update' => 'Actualizar las categorías del boletín',
		'nl_l_warning' => 'Ya existen %s boletínes basados en esta página. Es seguro que desea crear un más?',
		'nl_cat_msg1' => 'La página no tiene ningún elemento de contenido.',
		'nl_cat' => 'Elegir categorías',
		'nl_cat_msg2' => 'Elegir categorías para un elemento de contenido signífica que este elemento aparecerá en el boletín sólo cuando el destinario elige esta categoría en su perfil.<br />Si no elige ninguna categoría, el elemento aparecerá en todos les boletines.',
	),
	'nl' => Array (
		'dmail_noCreateAccess' => 'U kunt geen pagina\'s versturen die zijn verborgen of die beperkte toegang hebben.',
		'dmail_noRegular' => 'Dit type pagina kan niet als e-mail worden verzonden. Selecteer een geschikte pagina.',
		'dmail_dovsk_selectDmail' => 'Selecteer Direct Mail',
		'dmail_dovsk_crFromNL' => 'Maak een nieuwe Direct Mail van een nieuwsbrief',
		'dmail_msg1_crFromNL' => 'Er zijn nog geen nieuwsbrieven beschikbaar als Direct Mail!',
		'dmail_dovsk_crFromUrl' => 'Maak een nieuwe Direct Mail van een externe URL',
		'dmail_createMail' => 'Maak een e-mail',
		'dmail_view' => 'Bekijk Direct Mail record',
		'dmail_noEdit_noPerms' => 'Kan niet bewerken - u heeft geen permissie om Direct Mails te bewerken.',
		'dmail_noEdit_isSent' => 'Kan niet meer bewerken - e-mail is verzonden',
		'dmail_basedOn' => 'De Direct Mail is gebaseerd op deze pagina/nieuwsbrief.<br />Klik om de pagina-info te bekijken:',
		'dmail_menu_newsletters' => 'Nieuwsbrieven',
		'dmail_menu_direct_mails' => 'Direct Mails',
		'dmail_menu_quickMail' => 'QuickMail',
		'dmail_menu_list' => 'Adressenlijst',
		'dmail_menu_conf' => 'Module configuratie',
		'dmail_menu_mailerengine' => 'Mailer Engine Status',
		'dmail_menu_help' => 'Instructies',
		'dmailer_mid' => 'Taak nummer:',
		'dmailer_job_begin' => 'Taak begin',
		'dmailer_job_end' => 'Taak einde',
		'dmailer_invoked_at' => 'Gestart op',
		'dmailer_nothing_to_do' => 'Geen acties.',
		'dmailer_ending' => 'Afronding, verwerkingstijd:',
		'dmailer_sys_dmail_record' => 'sys_dmail record',
		'dmailer_processed' => 'verwerkt...',
		'dmail_menuItems' => '[MENU]',
		'dmail_menuItems_prefetch' => 'E-mailgegevens ophalen en samenstellen (url lezen)',
		'dmail_menuItems_testmail' => 'Zend een testmail',
		'dmail_menuItems_finalmail' => 'Bulk e-mail',
		'dmail_menuItems_stats' => 'Bekijk de statistieken van deze e-mail',
		'dmail_menuItems_options' => 'Opties:',
		'dmail_menuItems_note' => 'Opmerking:',
		'dmail_menuItems_note_use_menu' => 'Gebruik het menu om de inhoud van de e-mail op te halen',
		'dmail_menuItems_note_enter_sender' => 'U moet een \'Sender email\' adres voor de e-mail invoeren!',
		'dmail_menuItems_note_send_test' => 'Gebruik het menu om een test-mail naar uw eigen e-mailadres te sturen of stuur de e-mail naar alle geadresseerden.',
		'dmail_back' => '< TERUG',
		'dmail_yes' => 'JA',
		'dmail_no' => 'NEE',
		'dmail_error' => 'FOUT',
		'dmail_send' => 'Zend',
		'dmail_edit' => 'Bewerk',
		'dmail_cancel' => 'Annuleer',
		'dmail_number_records' => 'Aantal records:',
		'dmail_subject' => 'Onderwerp:',
		'dmail_write_subject' => '[onderwerp]',
		'dmail_HTML_url' => 'URL voor e-mail met HTML (webpagina opmaak):',
		'dmail_plaintext_url' => 'URL voor e-mail met gewone tekst:',
		'dmail_mailerengine_subject' => 'Onderwerp',
		'dmail_mailerengine_scheduled' => 'Gepland',
		'dmail_mailerengine_delivery_begun' => 'Aflevering begonnen',
		'dmail_mailerengine_delivery_ended' => 'Aflevering beëindigd',
		'dmail_mailerengine_number_sent' => '# verzonden',
		'dmail_mailerengine_invoked' => 'E-mail machine gestart!',
		'dmail_mailerengine_status' => 'Status van de e-mail machine',
		'dmail_mailerengine_current_time' => 'Huidig tijdstip:',
		'dmail_mailerengine_manual_invoke' => 'Start e-mail machine handmatig',
		'dmail_mailerengine_manual_explain' => 'Als Typo3 niet is ingesteld om automatisch de e-mail machine te starten, kan gestart worden door hier te klikken:',
		'dmail_mailerengine_invoke_now' => 'Start e-mail machine',
		'dmail_mailerengine_log' => 'Log:',
		'mailgroup_recip_from' => 'Geadresseerden uit groep:',
		'mailgroup_recip_number' => 'Aantal geadresseerden:',
		'mailgroup_list_all' => 'Lijst van alle geadresseerden',
		'mailgroup_table_address' => 'Adressen tabel',
		'mailgroup_table_fe_users' => 'Website gebruikers tabel',
		'mailgroup_plain_list' => 'Gewone lijst',
		'mailgroup_table_custom' => 'Maatwerk tabel',
		'mailgroup_download' => 'Download CSV bestand',
		'mailgroup_import' => 'Importeer CSV in de \'ADDRESS\' tabel',
		'mailgroup_import_rules' => 'Regels:',
		'mailgroup_import_test' => 'Test import (er worden geen gegevens verwerkt)',
		'mailgroup_import_now' => 'Importeer nu!',
		'recip_select_mailgroup' => 'Selecteer een e-mailgroep',
		'recip_create_mailgroup' => 'Nieuwe e-mailgroep',
		'recip_create_mailgroup_msg' => 'Nieuwe groep maken?',
		'recip_import_mailgroup' => 'Importeer',
		'recip_import_mailgroup_msg' => 'Klik hier om CSV te importeren',
		'prefetch_read_url' => 'U staat op het punt om de URL te lezen met de e-mailinhoud van deze URL\'s:',
		'prefetch_fetching' => 'Ophalen van de e-mailinhoud',
		'prefetch_patience' => 'Deze bewerking kan enige tijd in beslag nemen. Even geduld svp.',
		'prefetch_fetch' => 'Lees URL',
		'prefetch_error_choose' => 'U moet kiezen tussen zenden als HTML, als gewone tekst of beide. U heeft nog niets geselecteerd!',
		'testmail_individual' => 'Testmail - Individueel',
		'testmail_individual_msg' => 'Selecteer een geadresseerde voor de testmail. De e-mail wordt opgebouwd volgens het profiel van de geadresseerde.',
		'testmail_mailgroup' => 'Testmail - Direct Mail Groep',
		'testmail_mailgroup_msg' => 'Selecteer een geadresseerde mailgroep voor de testmail. De e-mails worden opgebouwd volgens de profielen van de geadresseerden in die groep.',
		'testmail_simple' => 'Testmail - Eenvoudig',
		'testmail_simple_msg' => 'Een eenvoudige testmail omvat alle e-mail elementen, ongeacht de categorie. Maar er worden geen gegevens naar de database geschreven. Voer een e-mailadres in waarop de testmail binnenkomt:',
		'send_sending' => 'E-mail wordt verzonden.',
		'send_was_sent' => 'E-mail is verzonden.',
		'send_was_sent_to_name' => 'De e-mail is verzonden naar <strong>%s</strong>.',
		'send_was_sent_to_number' => 'De e-mail is verzonden naar <strong>%s</strong> geadresseerden.',
		'send_recipients' => 'Geadresseerden:',
		'send_was_scheduled' => 'E-mail distributie schema',
		'send_was_scheduled_for' => 'De e-mail staat gepland voor distributie op',
		'schedule_select_mailgroup' => 'Selecteer een Mail Groep',
		'schedule_time' => 'Distributie tijdstip (hh:mm dd-mm-yy):',
		'schedule_send_all' => 'Zend aan alle abonnees in de Mail Groep',
		'schedule_list_emails' => 'Zend e-mail - lijst van e-mails',
		'schedule_enter_emails' => 'Voer de naam in van de geadresseerden. Scheid de adressen met nieuwe regel of komma ",":',
		'quickmail_message' => 'Bericht:',
		'quickmail_sender_name' => 'Naam afzender:',
		'quickmail_sender_email' => 'Afzender e-mail:',
		'quickmail_one_mail_bcc' => 'Een e-mail naar alle geadresseerden als bcc (men ziet elkaars e-mailadres niet)',
		'quickmail_one_mail_cc' => 'Een e-mail naar alle geadresseerden als cc (men kan elkaars e-mailadres zien)',
		'quickmail_many_mails' => 'Meerdere e-mails, een voor elke geadresseerde',
		'quickmail_send_now' => 'Zend het bericht onmiddelijk naar alle groepsleden',
		'quickmail_break_lines' => 'Breek de regels af bij 76 tekens:',
		'quickmail_missing_fields' => 'U heeft niet alle velden correct ingevuld!',
		'quickmail_sent_to' => 'Verzonden naar:',
		'quickmail_copy_to' => 'Kopie naar:',
		'quickmail_mode' => 'Stand:',
		'quickmail_no_recipient' => 'Geen geadresseerde.',
		'instructions_how' => 'Hoe dit werkt...',
		'instructions_text' => '
In deze module kunt u nieuwsbrieven maken (eigenlijk zijn dat webpagina\'s), die gemaild kunnen worden als \'direct mails\' naar geadresseerden op een abonneelijst.

Om een direct mail te maken, moet u deze stappen volgen:
<B>1)</B> Selecteer \'Nieuwsbrief\' in het menu hierboven.
    <B>2)</B> Maak een nieuwe \'nieuwsbrief\'. Voeg inhoud toe in de nieuwsbrief, sla deze op, controleer het met een preview - precies zoals u doet met normale webpagina\'s in TYPO3. Eigenlijk is een \'nieuwsbrief\' indeze context niets anders dan een TYPO3 webpagina bestemd voor e-mail verzending.
    <B>3)</B> Klik op de nieuwe nieuwsbrief in de lijst. Nu kunt u informatie zien over die pagina, en de inhoudselementen categoriseren.
    <B>4)</B> Als uw nieuwsbrief klaar is voor verzending, klik de link \'Maak nieuwe direct mail gebaseerd op deze pagina\' en een nieuwe direct mail gebaseerd op uw nieuwsbrief is gemaakt.
    <B>5)</B> Het eerste wat u moet doen met de nieuwe \'Direct Mail\' is de e-mailinhoud ophalen. Dit proces leest de inhoud van van de pagina en stelt de e-mail eruit samen.
    <B>6)</B> Zend eerst een test. U moet echt eerst een testmail aan uzelf sturen voordat de e-mail naar de abonnees gaat. Als u dat doet, bent u er zeker van dat de e-mail en de links die erin voorkomen correct zijn opgezet. Let op of er links in de e-mail voorkomen naar lokale netwerken. Deze zullen niet toegankelijk zijn voor voor de mensen die uw nieuwsbrief ontvangen!
    <B>7)</B> Start het zenden als alles in orde is.

    <B>Het verschil tussen een een nieuwsbrief en een direct mail</B>
    Een \'nieuwsbrief\' is eigenlijk een normale TYPO3 pagina die voorkomt in de direct mail module. U kunt de pagina bekijken in een browser en het gaat erom dat deze pagina uiteindelijk verzonden wordt als direct mail.
    Een \'direct mail\' is een record dat een samengestelde versie bevat van hetzij een nieuwsbrief pagina, hetzij de inhoud van een externe URL. Een direct mail bevat ook nog informatie zoals het e-mail onderwerp, bijlagen, prioriteit instellingen, antwoord adres enzovoort. Voor elke direct mail wordt bijgehouden wie de direct mail ontvangen heeft en wie heeft gereageerd.

    <B>Datavelden in direct mails:</B>
    U kunt gepersonaliseerde gegevens in de e-mails toevoegen door deze markers te gebruiken:
    ###USER_uid### (uniek id van de geadresseerde)
    ###USER_name### (volledige naam)
    ###USER_firstname### (voornaam, gecalculeerd)
    ###USER_title###
    ###USER_email###
    ###USER_phone###
    ###USER_www###
    ###USER_address###
    ###USER_company###
    ###USER_city###
    ###USER_zip###
    ###USER_country###
    ###USER_fax###

    ###SYS_TABLE_NAME###
    ###SYS_MAIL_ID###
    ###SYS_AUTHCODE###

    (Bovendien, ###USER_NAME### en ###USER_FIRSTNAME### voegen de namen in in hoofdletters)
',
		'stats_general_information' => 'Algemene informatie:',
		'stats_total' => 'Totaal:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Gewone tekst:',
		'stats_mails_sent' => 'Verzonden e-mails:',
		'stats_mails_returned' => 'Geretourneerde e-mails:',
		'stats_HTML_mails_viewed' => 'Geopende HTML e-mails:',
		'stats_unique_responses' => 'Unieke responses (link klik):',
		'stats_response' => 'Respons:',
		'stats_total_responses' => 'Totaal responsen (link klik):',
		'stats_links_clicked_per_respondent' => 'Aangeklikte links per respondent:',
		'stats_count' => 'Geteld:',
		'stats_total_mails_returned' => 'Totaal geretourneerde e-mails:',
		'stats_recipient_unknown' => 'Onbekende geadresseerde:',
		'stats_mailbox_full' => 'Mailbox vol:',
		'stats_bad_host' => 'Verkeerde host:',
		'stats_error_in_header' => 'Fout in Header:',
		'stats_reason_unkown' => 'Onbekende oorzaak:',
		'stats_list_returned' => 'Lijst van geretourneerde geadresseerden',
		'stats_disable_returned' => 'Zet de geretourneerde geadresseerden uit',
		'stats_CSV_returned' => 'CSV van geretourneerde geadresseerden',
		'stats_emails_returned_list' => 'E-mail adressen bij de geretourneerde e-mails:',
		'stats_mails_returned_unknown_recipient' => 'E-mails geretourneerd met onbekende geadresseerde:',
		'stats_list_returned_unknown_recipient' => 'Lijst van geretourneede geadresseerden met onbekende geadresseerde',
		'stats_disable_returned_unknown_recipient' => 'Zet geretourneerde geadresseerden uit met onbekende geadresseerde',
		'stats_CSV_returned_unknown_recipient' => 'CSV van geretourneerde geadresseerden met onbekende geadresseerde',
		'stats_emails_returned_unknown_recipient_list' => 'E-mail adressen van geretourneerde e-mails met onbekende geadresseerde:',
		'stats_mails_returned_mailbox_full' => 'E-mails geretourneerd met mailbox vol:',
		'stats_list_returned_mailbox_full' => 'Lijst van geretourneerde geadresseerden met mailbox vol',
		'stats_disable_returned_mailbox_full' => 'Zet geretourneerde geadresseerden uit met mailbox vol',
		'stats_CSV_returned_mailbox_full' => 'CSV van geretourneerde geadresseerden met mailbox vol',
		'stats_emails_returned_mailbox_full_list' => 'E-mail adressen van geretourneerde e-mails met mailbox vol:',
		'stats_mails_returned_bad_host' => 'E-mails geretourneerd met verkeerde host:',
		'stats_list_returned_bad_host' => 'Lijst van geretourneerde geadresseerden met verkeerde host',
		'stats_disable_returned_bad_host' => 'Zet geretourneerde geadresseerden uit met verkeerde host',
		'stats_CSV_returned_bad_host' => 'CSV van geretourneerde geadresseerden met verkeerde host',
		'stats_emails_returned_bad_host_list' => 'Email adresses of returned mails met verkeerde host:',
		'stats_mails_returned_bad_header' => 'E-mails geretourneerd met fout in de header:',
		'stats_list_returned_bad_header' => 'Lijst van geretourneerde geadresseerden met fout in de header',
		'stats_disable_returned_bad_header' => 'Zet geretourneerde geadresseerden uit met fout in de header',
		'stats_CSV_returned_bad_header' => 'CSV van geretourneerde geadresseerden met fout in de header',
		'stats_emails_returned_bad_header_list' => 'E-mail adressen van geretourneerde e-mails met fout in de header:',
		'stats_mails_returned_reason_unknown' => 'E-mails geretourneerd met onbekende oorzaak:',
		'stats_list_returned_reason_unknown' => 'Lijst van geretourneerde geadresseerden met onbekende oorzaak',
		'stats_disable_returned_reason_unknown' => 'Zet geretourneerde geadresseerden uit met onbekende oorzaak',
		'stats_CSV_returned_reason_unknown' => 'CSV van geretourneerde geadresseerden met onbekende oorzaak',
		'stats_emails_returned_reason_unknown_list' => 'E-mail adressen van geretourneerde e-mails met onbekende oorzaak:',
		'stats_emails_disabled' => 'uitgezette adressen',
		'stats_website_users_disabled' => 'uitgezette website gebruikers',
		'stats_direct_mail' => 'Statistieken van direct mail:',
		'stats_recalculate_stats' => 'Herbereken bewaarde statistieken',
		'stats_recalculate_cached_data' => 'Herbereken bewaarde gegevens:',
		'nl_select_msg1' => 'Er zijn geen pagina\'s in de e-mail module.',
		'nl_select' => 'Selecteer een nieuwsbrief',
		'nl_create' => 'Maak een nieuwsbrief',
		'nl_create_msg1' => 'Klik hier om een nieuwe pagina te maken die u later kunt versturen als een direct mail.',
		'nl_info' => 'Nieuwsbrief info',
		'nl_viewPage' => 'Bekijk pagina',
		'nl_editPage' => 'Bewerk pagina',
		'nl_createDmailFromPage' => 'Maak nieuwe direct mail op basis van deze pagina',
		'nl_alreadyBasedOn' => 'Deze e-mails zijn al gebaseerd op deze pagina!',
		'nl_l_subject' => 'Onderwerp',
		'nl_l_lastM' => 'Laatst gewijzigd',
		'nl_l_sent' => 'Verzonden?',
		'nl_l_size' => 'Omvang',
		'nl_l_attach' => 'Bijlage',
		'nl_l_type' => 'Type',
		'nl_l_tPage' => 'PAGINA',
		'nl_l_tUrl' => 'EXTERNE URL',
		'nl_l_column' => 'Kolom',
		'nl_l_ALL' => 'ALLE',
		'nl_l_ONLY' => 'UITSLUITEND',
		'nl_l_update' => 'Update categorie instellingen',
		'nl_l_warning' => 'Er zijn al %s Direct Mails op basis van deze nieuwsbrief. Weet u zeker dat u een andere wilt aanmaken?',
		'nl_cat_msg1' => 'Er zijn geen inhoudselementen op de pagina.',
		'nl_cat' => 'Selecteer categorieën',
		'nl_cat_msg2' => 'Categorieën instellen voor een inhoudselement betekent dat het element alleen in de e-mail verschijnt als de geadresseerde voor die categorie heeft gekozen in zijn profiel.<br />Als u geen categorie instelt voor een element, komt het element in alle e-mails terecht.',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
		'dmail_noCreateAccess' => 'Ne morete poslati strani, ki so skrite ali imajo omejen dostop.',
		'dmail_noRegular' => 'Tega tipa strani ne morete poslati po emailu. Prosimo izberite navadno stran.',
		'dmail_dovsk_selectDmail' => 'Izberi Direct Mail',
		'dmail_dovsk_crFromNL' => 'Ustvari nov Direct Mail iz okrožnice',
		'dmail_msg1_crFromNL' => 'Ni nobenih okrožnic, ki že niso v Direct Mail-u!',
		'dmail_dovsk_crFromUrl' => 'Ustvari nov Direct Mail iz zunanjega URLja',
		'dmail_createMail' => 'Ustvari sporoèilo',
		'dmail_view' => 'Poglej Direct Mail zapis',
		'dmail_noEdit_noPerms' => 'Urejanje ni mogoèe - nimate dovoljenja za urejanje Direct Mail-ov.',
		'dmail_noEdit_isSent' => 'Urejanje ni mogoèe - sporoèilo je bilo poslano',
		'dmail_basedOn' => 'Direct Mail izvira iz te strani/okrožnice.<br />Kliknite za ogled informacij o strani:',
		'dmail_edit' => 'Uredi',
		'nl_select_msg1' => 'V mail modulu ni nobenih strani.',
		'nl_select' => 'Izberite okrožnico',
		'nl_create' => 'Ustvarite okrožnico',
		'nl_create_msg1' => 'Kliknite tukaj za novo stran, ki jo boste kasneje lahko poslali kot Direct Mail.',
		'nl_info' => 'Informacije o okrožnici',
		'nl_viewPage' => 'Poglej stran',
		'nl_editPage' => 'Uredi stran',
		'nl_createDmailFromPage' => 'Ustvari nov Direct Mail iz te strani',
		'nl_alreadyBasedOn' => 'Ta sporoèila že izvirajo iz te strani!',
		'nl_l_subject' => 'Predmet',
		'nl_l_lastM' => 'Zadnja spr.',
		'nl_l_sent' => 'Poslano?',
		'nl_l_size' => 'Velikost',
		'nl_l_attach' => 'Priponka',
		'nl_l_type' => 'Tip',
		'nl_l_tPage' => 'STRAN',
		'nl_l_tUrl' => 'ZUN. URL',
		'nl_l_column' => 'Stolpec',
		'nl_l_ALL' => 'VSE',
		'nl_l_ONLY' => 'SAMO',
		'nl_l_update' => 'Osveži nastavitve kategorij',
		'nl_l_warning' => 'Na podlagi te okrožnice je ustvarjeno že %s Direct Mail-ov. Vseeno želite novega?',
		'nl_cat_msg1' => 'There are no content elements on the page.',
		'nl_cat' => 'Izberite kategorije',
		'nl_cat_msg2' => 'Izbira kategorij za element vsebine pomeni, da se bo ta element pojavil v sporoèilu le, èe je prejemnik v svoji nastavitvah izbral to kategorijo.<br />Èe za element ne izberete nobene kategorije, se bo pojavil v vseh sporoèilih.',
	),
	'fi' => Array (
		'dmail_noCreateAccess' => 'Et voi postittaa sivuja jotka ovat piilotettuja tai käytöltä rajattuja.',
		'dmail_noRegular' => 'Tätä sivutyyppiä ei voi lähettää sähköpostina. Ole ystävällinen ja valitse tavallinen sivu.',
		'dmail_dovsk_selectDmail' => 'Valitse Suora postitus.',
		'dmail_dovsk_crFromNL' => 'Luo uusi Suora Postitus uutislehdestä.',
		'dmail_msg1_crFromNL' => 'Ei ole uutislehtiä jotka eivät olisi jo Suora postituksessa!',
		'dmail_dovsk_crFromUrl' => 'Luo uusi Suora Postitus ulkoisesta URLista.',
		'dmail_createMail' => 'Lue sähköpostiviesti',
		'dmail_view' => 'Näytä Suora Postitus tietue.',
		'dmail_noEdit_noPerms' => 'Et voi muokata - Sinulla ei ole oikeuksia muokata Suora Postituksia.',
		'dmail_noEdit_isSent' => 'Et voi muokata - sähköposti on lähetetty.',
		'dmail_basedOn' => 'Suora Postitus perustuu tähän sivuun/uutislehteen.<br />Näpsäytä  nähdäksesi sivun tiedot:',
		'dmail_menu_newsletters' => 'Uutislehdet',
		'dmail_menu_direct_mails' => 'Suora Postitukset',
		'dmail_menu_quickMail' => 'PikaPostitus',
		'dmail_menu_list' => 'Vastaaottajalista',
		'dmail_menu_conf' => 'Aliohjelman asetukset',
		'dmail_menu_mailerengine' => 'Postitusohjelman tila',
		'dmail_menu_help' => 'Ohjeet',
		'dmailer_mid' => 'Työn numero:',
		'dmailer_job_begin' => 'Työn alku:',
		'dmailer_job_end' => 'Työn loppu:',
		'dmailer_invoked_at' => 'Käynnistetty',
		'dmailer_nothing_to_do' => 'Ei mitään suoritettavaa.',
		'dmailer_ending' => 'Lopetetaan, suoritusaika:',
		'dmailer_sys_dmail_record' => 'sys_dmail tietue',
		'dmailer_processed' => 'suoritettu...',
		'dmail_menuItems' => '[VALIKKO]',
		'dmail_menuItems_prefetch' => 'Hae ja valmistele postitustiedot (lue url)',
		'dmail_menuItems_testmail' => 'Lähetä testiposti',
		'dmail_menuItems_finalmail' => 'Lähetä massapostitus',
		'dmail_menuItems_stats' => 'Katsi tämän postin tilastot',
		'dmail_menuItems_options' => 'Vaihtoehdot:',
		'dmail_menuItems_note' => 'Huomautus:',
		'dmail_menuItems_note_use_menu' => 'Käytä valikko hakeaksesi postin sisällön',
		'dmail_menuItems_note_enter_sender' => 'Sinun on annettava \'Lähettäjän email\' osoitetälle postitukselle!',
		'dmail_menuItems_note_send_test' => 'Käytä valikko lähettääksesi testipostin omaan sähköpostiosoitteeseesi tai lähettääksesi postituksen kaikille vastaanottajille.',
		'dmail_back' => '< Takaisin',
		'dmail_yes' => 'Kyllä',
		'dmail_no' => 'Ei',
		'dmail_error' => 'Virhe',
		'dmail_send' => 'Lähetä',
		'dmail_edit' => 'Muokkaa',
		'dmail_cancel' => 'Peruuta',
		'dmail_number_records' => 'Tietueiden lukumäärä:',
		'dmail_subject' => 'Aihe:',
		'dmail_write_subject' => '[kirjoita aihe]',
		'dmail_HTML_url' => 'HTML URL:',
		'dmail_plaintext_url' => 'Pelkkä tekti URL:',
		'dmail_mailerengine_subject' => 'Aihe',
		'dmail_mailerengine_scheduled' => 'Aikautettu',
		'dmail_mailerengine_delivery_begun' => 'Jakelu alkoi',
		'dmail_mailerengine_delivery_ended' => 'Jakelu päättyi',
		'dmail_mailerengine_number_sent' => 'lähettetty',
		'dmail_mailerengine_invoked' => 'Postitus Ohjelma herätetty!',
		'dmail_mailerengine_status' => 'Postitus Ohjelman tila',
		'dmail_mailerengine_current_time' => 'Aika nyt:',
		'dmail_mailerengine_manual_invoke' => 'Herätä Postitus Ohjelma mannuaalisesti',
		'dmail_mailerengine_manual_explain' => 'Jos Typo3a ei ole asetettu herättämään Postitus Ohjelmaa automaattisesti voit herättää sen manuaalisesti näpsäyttämällä tästä:',
		'dmail_mailerengine_invoke_now' => 'Herätä Postitus Ohjelma',
		'dmail_mailerengine_log' => 'Loki:',
		'mailgroup_recip_from' => 'Vastaanottajat ryhmästä:',
		'mailgroup_recip_number' => 'Vastaanottajien lukumäärä:',
		'mailgroup_list_all' => 'Listaa kaikki vastaanottajat',
		'mailgroup_table_address' => 'Osoite taulukko',
		'mailgroup_table_fe_users' => 'Websivuston käyttäjä taulukkko',
		'mailgroup_plain_list' => 'Pelkkälista',
		'mailgroup_table_custom' => 'Itse muotoiltu taulu',
		'mailgroup_download' => 'Hae CSV tiedosto',
		'mailgroup_import' => 'Vie CSV tiedosto ADDRESS tauluun',
		'mailgroup_import_rules' => 'Säännöt:',
		'mailgroup_import_test' => 'Testaa vienti (tietoja ei kirjoiteta)',
		'mailgroup_import_now' => 'Vie nyt!',
		'recip_select_mailgroup' => 'Valitse PostitusRyhmä',
		'recip_create_mailgroup' => 'Uusi postitusryhmä',
		'recip_create_mailgroup_msg' => 'Luo uusi postitusryhmä?',
		'recip_import_mailgroup' => 'Vie',
		'recip_import_mailgroup_msg' => 'Näpsäytä tästä viedäksesi CSV tiedoston',
		'prefetch_read_url' => 'Oöet aikeissa likea url:in jossa postin sisältö seuraavista URL:eista:',
		'prefetch_fetching' => 'Haetaan postin sisältöjä',
		'prefetch_patience' => 'Tämä toiminto voi viedä hetken. Ole kärsivällinen.',
		'prefetch_fetch' => 'Luetaan URLia',
		'prefetch_error_choose' => 'Sinun täytyy valita lähetys joko HTML, pelkkänä tekstinä tai molemman muotoisina. Nyt ei ole valittu mitään!',
		'testmail_individual' => 'Testiposti - Yksittäinen',
		'testmail_individual_msg' => 'Valitse testipostin vastaanottaja. Postitus luodaan vastaanottajan profiiliin perustuen.',
		'testmail_mailgroup' => 'Testiposti - Suora Postitus ryhmä',
		'testmail_mailgroup_msg' => 'Valitse testipostin vastaanottaja ryhmä. Postitus luodaan vastaanottajien profiileihin perustuen.',
		'testmail_simple' => 'Testiposti - yksinkertainen',
		'testmail_simple_msg' => 'Yksinkertainen testiposti sisältää kaikki elemntiti luokasta riippumatta. Mutta USER_kenttiä EItäydennetä tiedoilla. Anna testipostia varten sähköpostiosoite:',
		'send_sending' => 'Lähetetään postia.',
		'send_was_sent' => 'Postitus lähetettiin.',
		'send_was_sent_to_name' => 'Postitus lähetettiin <strong>%s</strong>.',
		'send_was_sent_to_number' => 'Postitus lähetettiin <strong>%s</strong> vastaanottajille.',
		'send_recipients' => 'Vastaaonttajat:',
		'send_was_scheduled' => 'Postitus valmisteltu jakeluun',
		'send_was_scheduled_for' => 'Postitus valmisteltu jakeluun kello',
		'schedule_select_mailgroup' => 'Valitse postitusryhmä',
		'schedule_time' => 'Jakelu aika (hh:mm pp-kk-vv):',
		'schedule_send_all' => 'Lähetä kaikille tilaajille paostitusryhmässä',
		'schedule_list_emails' => 'Lähetä postitus - email osoiteet listana',
		'schedule_enter_emails' => 'Anna vastaanottajien sähköpostiosoitteet. Erottele osoitteet rivinvaihdolla tai pilkulla:',
		'quickmail_message' => 'Viesti:',
		'quickmail_sender_name' => 'Lähettäjän nimi:',
		'quickmail_sender_email' => 'Lähettäjän sähköpostiosoite:',
		'quickmail_one_mail_bcc' => 'Yksi posti jokaiselle vastaanottajalle tiedossa Blind Carbon Copy (Bcc)',
		'quickmail_one_mail_cc' => 'Yksi posti kaikille vastaanottajille tiedossa Carbon Copy (Cc)',
		'quickmail_many_mails' => 'Monta posti, yksi jokaiselle vastaanottajalle',
		'quickmail_send_now' => 'Lähetä viesti kaikille ryhmän jäsenille välittömästi',
		'quickmail_break_lines' => 'Rivin katkaisu 76:n merkin jälkeen:',
		'quickmail_missing_fields' => 'Et täyttänyt kaikkia tietoja oikein!',
		'quickmail_sent_to' => 'Lähetetty:',
		'quickmail_copy_to' => 'Kopio:',
		'quickmail_mode' => 'Tapa:',
		'quickmail_no_recipient' => 'Ei vastaanottajia.',
		'configure_direct_mail_module' => 'Konfiguroi suora postitus aliohjelma',
		'instructions_how' => 'Kuinka tämä toimii ...',
		'instructions_text' => 'Tällä modulilla voit luoda uutislehtiä (sivuja), jotka voidaan epostittaa ns. suorapostituksena henkilöille jotka ovat tilaajalistalla.  Luodaksesi suorapostituksen, Sinun tulee noudattaa seuraavia askelia: <B>1)</B> Valitse \'Uutislehti\' ylläolevasta valikosta <B>2)</B> Luo uusi \'uutislehti\'. Tee sisältö tähän uutislehteen, tallenna se, esikatsele - aivan samoin kuin olet tottunut tekemään tavallisia sivuka Typo3:ssa. Todellisuudessa \'uutislehti\' on yksinkertaisesti Typo3 sivuja, jotka on tarkoitettu sähköpostiin! <B>3)</B> Näpsäytä uutta uutislehteäsi listalla. Nyt voit nähdä sivun informaation. ja luokitella sisältö elementit. <B>4)</B> Kun uutislehtesi on valmis jakeluun, näpsäytä linkkiä \'Luo uusi suora postitus perustuen tähän sivuun\' ja uusi suora postitus joka perustuu tähän uuteen uutislehteen on luotu. <B>5)</B> Ensimmäinen asia uuteen suora postitukseesi on hakea postiin sisältö. Tämä prosessi lukee sivun sisällönja muotoilee siitä postin sisällön. <B>6)</B> Lähetä tesit. Sinun on ehdottomasti lähetettävä posti ensin itsellesi ennen kuin lähetät sitä tilaajille. Näin voit varmistua että posti ja kaikki linkit on oikein asetettu. Ole varuillasi jos linkkejä on asetettu paikallisen verkon URLeihin. Ne eivät ole käytettävissä henkilöillaä jotka saavat uutislehtesi! <B>7)</B> Käynnistä jakelu jos kaikki on oikein.  <B>Uutislehden ja suora postituksen erotl</B> Uutislehti on periaatteessa tavallinen Typo3 sivu joka sijaitsee tässä suora postitus modulissa. Voit selailla sivua selaimella ja lopullisena ideana on ett lähetät sen suora postituksella. Suora Postitus on tietue joka sisältää lähetettävän version uutislehti sivusta tai vaihtoehtoisesti linkin ulkoisen URLin (osoitetteen) sivuun. Lisäksi Suora postitus sisältää muita tietoja kuten postin otsikon , kaikki liitteet, prioriteetti asetukset, vastausosoitteet jne. Jokaista postitusta varten pidetään lokia josta selviävät vastaanottajien tiedot, ovatko saaneet ja ovatko vastanneet.  <B>Tietokentät suora postituksissaa:</B> Voit lisätä henkilökohtaisia tietoja postiin näillä markkereilla: ###USER_uid### (vastaanottajan yksilöllinen ID) ###USER_name### (koko nimi) ###USER_firstname### (etunimi) ###USER_title### ###USER_email### ###USER_phone### ###USER_www### ###USER_address### ###USER_company### ###USER_city### ###USER_zip### ###USER_country### ###USER_fax###  ###SYS_TABLE_NAME### ###SYS_MAIL_ID### ###SYS_AUTHCODE###  (Lisäksi ###USER_NAME### and ###USER_FIRSTNAME### lisäävät ison kirjaimin vastaavat tiedot)',
		'stats_general_information' => 'Yleiset tiedot:',
		'stats_total' => 'Yhteensä:',
		'stats_HTML' => 'HTML:',
		'stats_plaintext' => 'Pelkkä teksti:',
		'stats_mails_sent' => 'Postejä lähetetty:',
		'stats_mails_returned' => 'Posteja palautunut:',
		'stats_HTML_mails_viewed' => 'HTML posteja katsottu:',
		'stats_unique_responses' => 'Erilliset vastaukset (linkki klikkaus):',
		'stats_response' => 'Vastaus:',
		'stats_total_responses' => 'Vastauksia yhteensä (linkki klikkaus):',
		'stats_links_clicked_per_respondent' => 'Linkkejä klikattu per vastaanottaja:',
		'stats_count' => 'Lukumäärä:',
		'stats_total_mails_returned' => 'Posteja palautunut yhteensä:',
		'stats_recipient_unknown' => 'Vastaanottaja tuntematon:',
		'stats_mailbox_full' => 'Mailboxi täysi:',
		'stats_bad_host' => 'Väärä isäntä (host):',
		'stats_error_in_header' => 'Virhe headerissä:',
		'stats_reason_unkown' => 'Tuntematon syy:',
		'stats_list_returned' => 'Listaa palautuneet vastaanottajat',
		'stats_disable_returned' => 'Estä palautuneet vastaanottajat',
		'stats_CSV_returned' => 'CSV lista palautuneista vastaanottajista',
		'stats_emails_returned_list' => 'Sähköpostiosoitteet palautuneista vastaanottajista:',
		'stats_mails_returned_unknown_recipient' => 'Postit jotka ovat palautuneet tuntemattomista vastaanottajista:',
		'stats_list_returned_unknown_recipient' => 'Lista palautuneista tuntemattomista vastaanottajista:',
		'stats_disable_returned_unknown_recipient' => 'Estä palautuneet tuntemattomattomat vastaanottajat:',
		'stats_CSV_returned_unknown_recipient' => 'CSV lista palautuneista tuntemattomista vastaanottajista',
		'stats_emails_returned_unknown_recipient_list' => 'Sähköpostiosoitteet palautuneista tuntemattomista vastaanottajista:',
		'stats_mails_returned_mailbox_full' => 'Postit jotka palautuneet mailbox täysi:',
		'stats_list_returned_mailbox_full' => 'Lista vastaanottajista mailbox täysi:',
		'stats_disable_returned_mailbox_full' => 'Estä vastaanottajat mailbox täysi:',
		'stats_CSV_returned_mailbox_full' => 'CSV lista vastaanottajat mailbox täysi:',
		'stats_emails_returned_mailbox_full_list' => 'Sähköpostiosoitteet palautuneista vastaanottajista mailbox täysi:',
		'stats_mails_returned_bad_host' => 'Postit jotka palautuneet väärä isäntä (host):',
		'stats_list_returned_bad_host' => 'Lista vastaanottajat jotka palautuneet väärä isäntä (host):',
		'stats_disable_returned_bad_host' => 'Estä vastaanottajat jotka palautuneet väärä isäntä (host):',
		'stats_CSV_returned_bad_host' => 'CSV lista vastaanottajat jotka palautuneet väärä isäntä (host):',
		'stats_emails_returned_bad_host_list' => 'Sähköpostiosoitteet vastaanottajat jotka palautuneet väärä isäntä (host):',
		'stats_mails_returned_bad_header' => 'Postit jotka palautuneet virheellinen header:',
		'stats_list_returned_bad_header' => 'Listaa vastaanottajat jotka palautuneet virheellinen header:',
		'stats_disable_returned_bad_header' => 'Estä vastaanottajat jotka palautuneet virheellinen header:',
		'stats_CSV_returned_bad_header' => 'CSV lista vastaanottajat jotka palautuneet virheellinen header:',
		'stats_emails_returned_bad_header_list' => 'Sähköpostiosoitteet vastaanottajat jotka palautuneet virheellinen header:',
		'stats_mails_returned_reason_unknown' => 'Postit jotka palautuneet tuntematon virhe:',
		'stats_list_returned_reason_unknown' => 'Listaa vastaanottajat jotka palautuneet tuntematon virhe:',
		'stats_disable_returned_reason_unknown' => 'Estä vastaanottajat jotka palautuneet tuntematon virhe:',
		'stats_CSV_returned_reason_unknown' => 'CSV lista vastaanottajat jotka palautuneet tuntematon virhe:',
		'stats_emails_returned_reason_unknown_list' => 'Sähköpostiosoitteet vastaanottajat jotka palautuneet tuntematon virhe:',
		'stats_emails_disabled' => 'estetyt osoitteet',
		'stats_website_users_disabled' => 'estetyt sivuston käyttäjät',
		'stats_direct_mail' => 'Suora Postituksen tilastot:',
		'stats_recalculate_stats' => 'Laske uudelleen välimuistin tilasto tiedot:',
		'stats_recalculate_cached_data' => 'Laske uudelleen välimuisti tiedot:',
		'nl_select_msg1' => 'Postitus modulissa ei ole sivuja.',
		'nl_select' => 'Valitse uutislehti',
		'nl_create' => 'Luo uutislehti',
		'nl_create_msg1' => 'Näpsäytä tästä luodaksesi uuden sivun jonka myöhemmin voit lähettää suora postituksena.',
		'nl_info' => 'Uutislehden tiedot',
		'nl_viewPage' => 'Näytä sivu',
		'nl_editPage' => 'Muokkaa sivua',
		'nl_createDmailFromPage' => 'Luo uusi Suora Postitus joka perustuu tähän sivuun',
		'nl_alreadyBasedOn' => 'Nämä postitukset perustuvat jo tähän sivuun!',
		'nl_l_subject' => 'Aihe',
		'nl_l_lastM' => 'Viimeksi muokattu',
		'nl_l_sent' => 'Lähetetty ?',
		'nl_l_size' => 'Koko',
		'nl_l_attach' => 'Liite',
		'nl_l_type' => 'Tyyppi',
		'nl_l_tPage' => 'SIVU',
		'nl_l_tUrl' => 'Ulkoinen URL',
		'nl_l_column' => 'Sarake',
		'nl_l_ALL' => 'KAIKKI',
		'nl_l_ONLY' => 'AINOASTAAN',
		'nl_l_update' => 'Päivitä luokka asetuksia',
		'nl_l_warning' => 'On jo %s Suora Postitusta jotka perustuvat tähän uutislehteen. Oletko varma että haluat luoda uuden ?',
		'nl_cat_msg1' => 'Sivulla ei ole sisältöelementtejä.',
		'nl_cat' => 'Valitse luokat',
		'nl_cat_msg2' => 'Kun sisältö elementille asetetaan luokka tarkoittaa se että seotetaan mukaan postiin vain jos vastaanottaja on valinnut tämän luokan profiiliinsa.<br>Jos et aseta mitään luokkaa elementtiin, otetaan se mukaan kaikkiin postituksiin.',
	),
	'tr' => Array (
		'dmail_noCreateAccess' => 'Gizli veya eriþim engelli sayfalarý postalayamazsýnýz.',
		'dmail_noRegular' => 'Bu sayfa türünü email olarak gönderemezsiniz. Lütfen düzenli bir sayfa seçin.',
		'dmail_dovsk_selectDmail' => 'Doðrudan mail seçimi',
		'dmail_dovsk_crFromNL' => 'Haber mektubundan yeni bir Doðrudan Mail yaratýn',
		'dmail_msg1_crFromNL' => 'Henüz Doðrudan Mail olarak sunulan haber mektuplarý bulunmamaktadýr!',
		'dmail_dovsk_crFromUrl' => 'Dýþ URL den yeni Doðrudan Mail yaratýn',
		'dmail_createMail' => 'Mail yarat',
		'dmail_view' => 'Doðrudan mail kayýtýný göster',
		'dmail_noEdit_noPerms' => 'Düzenlenemiyor - Doðrudan Mailleri düzeltmeye yetkiniz yok.',
		'dmail_noEdit_isSent' => 'Düzenlenemiyor - mail gönderilmiþtir',
		'dmail_basedOn' => 'Doðrudan Mail bu sayfaya/haber mektubu na dayanýyor.<br />Sayfa bilgisini görmek için týklayýnýz:',
		'dmail_edit' => 'Düzenle',
		'nl_select_msg1' => 'Mail modülünde sayfa bulunmamaktadýr.',
		'nl_select' => 'Bir haber mektubu seç',
		'nl_create' => 'Bir haber mektubu yarat',
		'nl_create_msg1' => 'Sonradan doðrudan mail olarak gönderebilmeniz için yeni bir sayfa yaratamaya týklayýnýz.',
		'nl_info' => 'Haber mektubu bilgisi',
		'nl_viewPage' => 'Sayfa göster',
		'nl_editPage' => 'Sayfa düzelt',
		'nl_createDmailFromPage' => 'Bu sayfaya dayanarak yeni doðrudan mail yarat',
		'nl_alreadyBasedOn' => 'Mailler bu sayfaya dayandýrýlýyor!',
		'nl_l_subject' => 'Konu',
		'nl_l_lastM' => 'Son modül.',
		'nl_l_sent' => 'Gönder?',
		'nl_l_size' => 'Ebat',
		'nl_l_attach' => 'Ýliþtir.',
		'nl_l_type' => 'Tür',
		'nl_l_tPage' => 'SAYFA',
		'nl_l_tUrl' => 'DIÞ URL',
		'nl_l_column' => 'Sütun',
		'nl_l_ALL' => 'HEPSÝ',
		'nl_l_ONLY' => 'TEK',
		'nl_l_update' => 'Kategori ayarlarýný güncelle',
		'nl_l_warning' => 'Bu Doðrudan Mailler %s bu haber mektubuna dayanýyor. Bir baþkasýný yaratmak istediðinizden emin misiniz?',
		'nl_cat_msg1' => 'Bu sayfa üzerinde içerik elemaný bulunmamaktadýr.',
		'nl_cat' => 'Kategorileri seç',
		'nl_cat_msg2' => 'Eðer alýcý kendi profilindeki kategoriyi seçerse içerik elemaný için ayar kategorilerinin elemaný olan nesne sadece mail içinde görünecektir.<br />Eðer nesne için kategori kurmazsanýz, nesne tüm maillerde görünecektir.',
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'dmail_noCreateAccess' => 'Você não pode enviar páginas ocultas ou com restrição de acesso.',
		'dmail_noRegular' => 'Este tipo de página não pode ser enviada como e-mail. Por favor selecione uma página comum.',
		'dmail_dovsk_selectDmail' => 'Selecionar Mala Direta',
		'dmail_dovsk_crFromNL' => 'Criar uma nova Mala Direta a partir do informativo',
		'dmail_msg1_crFromNL' => 'Não há informativos que já não estejam presentes como Mala Direta!',
		'dmail_dovsk_crFromUrl' => 'Criar uma nova Mala Direta a partir de uma URL externa',
		'dmail_createMail' => 'Criar mensagem',
		'dmail_view' => 'Ver registros de mala direta',
		'dmail_noEdit_noPerms' => 'Não editável - você não possui permissão para editar Malas Diretas.',
		'dmail_noEdit_isSent' => 'Não editável - mensagem já enviada',
		'dmail_basedOn' => 'A Mala Direta é baseada nesta página/informativo.<br/>Clique para ver informação da página:',
		'dmail_menu_newsletters' => 'Informativos',
		'dmail_menu_direct_mails' => 'Malas Diretas',
		'dmail_menu_quickMail' => 'MalaRápida',
		'dmail_menu_list' => 'Lista de destinatários',
		'dmail_menu_conf' => 'Configuração do módulo',
		'dmail_menu_mailerengine' => 'Status do Sistema de Envio',
		'dmail_menu_help' => 'Instruções',
		'dmailer_mid' => 'Trabalho No:',
		'dmailer_job_begin' => 'Início do trabalho',
		'dmailer_job_end' => 'Término do trabalho',
		'dmailer_invoked_at' => 'Ativado em',
		'dmailer_nothing_to_do' => 'Nada a fezer.',
		'dmailer_ending' => 'Final, parsetime:',
		'dmailer_sys_dmail_record' => 'registro sys_dmail',
		'dmailer_processed' => 'processado',
		'dmail_menuItems' => '[MENU]',
		'dmail_menuItems_prefetch' => 'Pegar e compilar dados de e-mail (ler url)',
		'dmail_menuItems_testmail' => 'Enviar mensagem de teste',
		'dmail_menuItems_finalmail' => 'Enviar mensagem em massa',
		'dmail_menuItems_stats' => 'Ver estatísticas desta mensagem',
		'dmail_menuItems_options' => 'Opções:',
		'dmail_menuItems_note' => 'Anotação:',
		'dmail_menuItems_note_use_menu' => 'Use o menu para buscar conteúdo para o e-mail',
		'dmail_menuItems_note_enter_sender' => 'Você deve inserir um endereço "E-mail do remetente" para a mensagem!',
		'dmail_menuItems_note_send_test' => 'Use o menu para enviar uma mensagem-teste para seu próprio endereço de e-mail ou finalmente envie a mensagem para todos os destinatários.',
		'dmail_back' => '< VOLTAR',
		'dmail_yes' => 'SIM',
		'dmail_no' => 'NÃO',
		'dmail_error' => 'ERRO',
		'dmail_send' => 'Enviar',
		'dmail_edit' => 'Editar',
		'dmail_cancel' => 'Cancelar',
		'dmail_number_records' => 'Número de registros:',
		'dmail_subject' => 'Assunto:',
		'dmail_write_subject' => '[escrever assunto]',
		'dmail_HTML_url' => 'URL HTML:',
		'dmail_plaintext_url' => 'URL Puro Texto',
		'dmail_mailerengine_subject' => 'Assunto',
		'dmail_mailerengine_scheduled' => 'Agendado',
		'dmail_mailerengine_delivery_begun' => 'Envio começou em',
		'dmail_mailerengine_delivery_ended' => 'Envio terminou em',
		'dmail_mailerengine_number_sent' => '# enviados',
		'dmail_mailerengine_invoked' => 'Ferramenta de Email Ativada!',
		'dmail_mailerengine_status' => 'Situação da Ferramente de Email',
		'dmail_mailerengine_current_time' => 'Horário atual:',
		'dmail_mailerengine_manual_invoke' => 'Ativar Ferramenta Manualmente',
		'dmail_mailerengine_manual_explain' => 'Se o Typo3 não estiver configurado para chamar a Ferramente de Email automaticamente, você pode ativá-la clicando aqui:',
		'dmail_mailerengine_invoke_now' => 'Ativar Ferramenta de Email',
		'dmail_mailerengine_log' => 'Log:',
		'mailgroup_recip_from' => 'Cadastros do grupo:',
		'mailgroup_recip_number' => 'Número de cadastros:',
		'mailgroup_list_all' => 'Listar todos os cadastros',
		'mailgroup_table_address' => 'Tabela de Endereços',
		'mailgroup_table_fe_users' => 'Tabela de Usuários do Site',
		'mailgroup_plain_list' => 'Lista Simples',
		'mailgroup_table_custom' => 'Tabela Personalizada',
		'mailgroup_download' => 'Baixar arquivo CSV',
		'mailgroup_import' => 'Importar CSV para a tabela "ENDEREÇO"',
		'mailgroup_import_rules' => 'Regras:',
		'mailgroup_import_test' => 'Testar importação (dados não serão gravados)',
		'mailgroup_import_now' => 'Importar agora!',
		'recip_select_mailgroup' => 'Selecione um Grupo de Mail',
		'recip_create_mailgroup' => 'Novo Grupo de Mail',
		'recip_create_mailgroup_msg' => 'Criar novo grupo?',
		'recip_import_mailgroup' => 'Importar',
		'recip_import_mailgroup_msg' => 'Clique aqui para importar CSV',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>